define([], function () {
  return {
      "Users": "Users",
      "Organs": "Organs",
      "properties": "properties",
      "List": "List",
      "Templates": "Templates",
      
      // ORGAN prodPERTIES
      "DepartmentName": "Organ Name",
      "DepartmentNamePlaceholder": "Select an organ",
      "OrganType": "Organ Type",
      "GeneralPlaceholder": "Select a value",
      "Ministry": "Ministry",
      "Nomenclature": "Nomenclature",
      "Secretaria": "Secretariat",
      "Intersectorial": "Intersectorial",
      "BusinessArea": "Sectorial area",
      "Subject":"Subject",
      "Abbreviation": "Abbreviation",
      "Legislature": "Legislature",
      "CreationDate": "Creation Date",
      "ExpirationDate": "Expiration Date",
      "DaysToApprodve": "Days to approdve the minutes",
      "SIA": "SIA",
      "DIR3": "DIR3",
      "Description": "Description",
      "Observations": "Observations",
      "ActiveStatus": "Status",
      "ActiveYes": "Active",
      "ActiveNo": "Inactive",
      "IntersectorialYes": "Yes",
      "IntersectorialNo": "No",
      "SelectOrgan":"Select an existing term",
      "CreateNewOrgan":"Create a new term",
      "DepartmentNameExist": "Another organ with this name already exists.",
      "CodigoDepartment": "Organ code",
      "FechaInscripcion": "Registration date",
      "StatusDepartment": "Situation",
      // USER prodPERTIES
      "Name": "Name",
      "SurName": "Surname",
      "DisplayName": "Display Name",
      "Email": "Email",
      "SecondaryMail": "Secondary Email",
      "PhoneNumber": "Mobile Phone",
      "Job": "Job",
      "AutonomousCommunity": "Autonomous Community",
      "Status": "Status",
      "CompanyNameLabel": "Ministry / Regional Government",
      "DepartmentLabel": "Unit / Department",
      "EmployeeTypeLabel": "Employee Type",
      "BusinessPhoneLabel": "Business Phone",

      "InvitationMessage": "Invitation message",
      "InvitationCCO": "Invitation BCC recipient",

      "FieldRequired":"This field is required.",
      "PhoneError":"You must enter a valid phone number (9 consecutive digits, without spaces or other characters).",
      "MailError":"You must enter a valid email (format: user@domain.extension).",

      // USER / ORGAN LIST
      "Members": "Members",
      "Role": "Roles",
      "Remove": "Remove",
      "AddNewUser": "Add User",
      "AddNewOrgan": "Add Organ",
      "SelectUserPlaceholder": "Select a user",
      "SelectOrganPlaceholder": "Select an organ",
      "SelectRolePlaceholder": "Select a role",
      "SelectCCAAPlaceholder": "Select a community",
      "NeedLicense": "The user will have limited functionality without a license",
      
      "ChangesDone": "The following changes will be made:",
      "AreYouSure": "Are you sure you want to make these changes?",
      "NoChanges": "No changes have been made",
      "ECNTyValueChange":"(eCNTy)",
      "SavingLoading": "Updating information",
      "RemovedListItem": "Removed",
      "ErrorListOrgan": "There are duplicate users, review the changes before saving.",
      "ErrorListUser": "There are duplicate organs, review the changes before saving.",
      "UserDuplicated": "There is already an entry for this user in the organ.",
      "OrganDuplicated": "There is already an entry for this organ in the user.",
      "CheckPermissionsTooltip": "Check if the user's permissions have been applied correctly",
      "UserLabel": "User",
      "OrganLabel": "Organ",
      "RoleLabel": "Role",
      "CheckPermissionsLabel": "Permissions check",
      "UserHasPermissionsTxt": "The user has permissions for the specified role",
      "UserNotPermissionsTxt": "The user does not yet have permissions for the specified role",
      "Accept": "Accept",
      "PermissionsTimeNote": "These changes may take several minutes to take effect.",
      "Warning": "Warning",
      "WarningMessage": "Changes made may take a few minutes to be reflected.",
      
      "ErrorMsg": "An error has occurred, please try again later.",
      "Save": "Save",
      "Discard": "Discard",
      "Close": "Close",
      "StatusOk": "OK",
      "StatusError": "Error",
      "StatusPending": "processing",
      "AsignOrganRoleTooltip": "*To assign a user to an organ, it will be necessary to select an organ and ensure the user has the 'Role' field filled in.",
      "OrganRoleMandatoryTooltip": "*The 'Role' field is mandatory to process the user.",
      "DownloadTemplate": "Download template",
      "UsersNotprocessed": "One or more users have not been processed: The 'Role' field is mandatory.",
      "NoUsersLoaded": "No users loaded",
      "MandatoryFieldsWarning": "The 'Name', 'Surname', and 'Email' fields are mandatory",
      "MandatoryFieldOrgans": "The 'Name', 'Surname', 'Email' and 'Role' fields are mandatory",
      
      "MaxLong64": "The field cannot exceed 64 characters",
      "MaxLong128": "The field cannot exceed 128 characters",
      "MandatoryLengthFields": "* The fields 'First name', 'Last name', 'Autonomous community', 'Ministry/Regional Government', 'Unit/Department', 'Position' and 'Employee type' have a maximum length of 64 characters."
  }
})