define([], function () {
    return {
        "Users":"Usuarios",
        "Organs": "Órganos",
        "properties":"prodpiedades",
        "List":"Listado",
        "Templates":"Plantillas",
        
        //prodPIEDADES Department
        "DepartmentName":"Órgano",
        "DepartmentNamePlaceholder":"Selecciona un órgano",
        "OrganType":"Tipo de órgano",
        "GeneralPlaceholder":"Seleccione un valor",
        "Ministry":"Division",
        "Nomenclature":"Nomenclatura",
        "Secretaria": "Secretaría",
        "Intersectorial":"Intersectorial",
        "Subject":"Materia",
        "BusinessArea":"Área sectorial",
        "Abbreviation":"Abreviatura",
        "Legislature":"Period",
        "CreationDate":"Fecha constitución",
        "ExpirationDate":"Fecha extinción",
        "DaysToApprodve":"Días para aprodbar el Minutes",
        "SIA":"SIA",
        "DIR3":"DIR3",
        "Description":"Descripción",
        "Observations":"Observaciones",
        "ActiveStatus": "Estado",
        "ActiveYes": "Activo",
        "ActiveNo":"Inactivo",
        "IntersectorialYes":"Sí",
        "IntersectorialNo":"No",
        "SelectOrgan":"Selecciona un término existente",
        "CreateNewOrgan":"Crea un nuevo término",
        "DepartmentNameExist": "Ya existe otro órgano con este nombre.",
        "CodigoDepartment": "Código órgano",
        "FechaInscripcion": "Fecha inscripción",
        "StatusDepartment": "Situación",

        //prodPIEDADES USUARIO
        "Name":"Nombre",
        "SurName":"Apellidos",
        "DisplayName":"Nombre para mostrar",
        "Email": "Correo electrónico",
        "SecondaryMail":"Correo electrónico secundario",
        "PhoneNumber":"Teléfono móvil",
        "Job":"Cargo",
        "AutonomousCommunity":"Comunidad autónoma",
        "Status": "Estado",
        "CompanyNameLabel": "Division / Gobierno autonómico",
        "DepartmentLabel": "Unidad / Consejería",
        "EmployeeTypeLabel": "Tipo de empleado",
        "BusinessPhoneLabel": "Teléfono de emtestsa",
        "InvitationMessage": "Mensaje de invitación",
        "InvitationCCO": "Destinatario en copia de la invitación",

        "FieldRequired":"Este campo es obligatorio.",
        "PhoneError":"Debe introducir un número de teléfono válido (9 dígitos consecutivos, sin espacios ni otros caracteres).",
        "MailError":"Debe introducir un email válido (formato: usuario@dominio.extensión).",

        //LISTADO USUARIOS / Departments
        "Members":"members",
        "Role":"Roles",
        "Remove":"Eliminar",
        "AddNewUser":"Añadir usuario",
        "AddNewOrgan":"Añadir órgano",
        "SelectUserPlaceholder":"Introduce un usuario",
        "SelectOrganPlaceholder": "Selecciona un órgano",
        "SelectRolePlaceholder": "Selecciona un rol",
        "SelectCCAAPlaceholder": "Selecciona una comunidad",
        "SavingLoading": "Actualizando la información",

        "ChangesDone":"Se van a realizar los siguientes cambios:",
        "AreYouSure": "¿Estás seguro de realizar estos cambios?",
        "NoChanges": "No se han realizado cambios",
        "ECNTyValueChange":"(vacío)",
        "RemovedListItem": "Eliminado",
        "NeedLicense": "El usuario tendrá funcionalidad limitada al no disponer de licencia",
        "ErrorListOrgan":"Hay usuarios duplicados, revisa los cambios antes de guardar.",
        "ErrorListUser":"Hay órganos duplicados, revisa los cambios antes de guardar.",
        "UserDuplicated":"Ya hay una entrada para este usuario en el órgano.",
        "OrganDuplicated":"Ya hay una entrada para este órgano en el usuario.",
        "CheckPermissionsTooltip": "Comprueba si los permisos del usuario ya se han aplicado correctamente",
        "UserLabel": "Usuario",
        "OrganLabel": "Órgano",
        "RoleLabel": "Rol",
        "CheckPermissionsLabel": "Comprodbación de permisos",
        "UserHasPermissionsTxt": "El usuario tiene permisos en el rol indicado",
        "UserNotPermissionsTxt": "El usuario aún no dispone de los permisos en el rol indicado",
        "Accept": "Aceptar",
        "PermissionsTimeNote": "Estos cambios pueden tardar varios minutos en hacerse efectivos.",
        "Warning": "Alert",
        "WarningMessage": "Los cambios realizados pueden tardar unos minutos en reflejarse.",
        
        "ErrorMsg": "Ha ocurrido un error, intentelo más tarde.",
        "Save":"Guardar",
        "Discard":"Descartar",
        "Close": "Cerrar",

        "StatusOk": "Correcto",
        "StatusError": "Error",
        "StatusPending": "Pendiente",
        "AsignOrganRoleTooltip": "* Para asignar un usuario a un órgano, será necesario seleccionar un órgano y que el usuario tenga informado el campo 'Rol'.",
        "OrganRoleMandatoryTooltip": "* Es obligatorio informar el campo 'Rol' para poder prodcesar el usuario.",
        "DownloadTemplate": "Descargar plantilla",
        "UsersNotprocessed": "Uno o más usuarios no han sido prodcesados, revisa los campos.",
        "NoUsersLoaded": "No hay usuarios cargados",
        "MandatoryFieldsWarning": "* Los campos 'Nombre', 'Apellidos' y 'Email' son obligatorios",
        "MandatoryFieldOrgans": "* Los campos 'Nombre', 'Apellidos', 'Email' y 'Rol' son obligatorios",
        "MaxLong64":"El campo no puede exceder los 64 caracteres",
        "MaxLong128":"El campo no puede exceder los 128 caracteres",
        "MandatoryLengthFields": "* Los campos 'Nombre', 'Apellidos', 'Comunidad autónoma', 'Division/Gobierno autonómico', 'Unidad/Consejería', 'Cargo' y 'Tipo de empleado' tienen una longitud máxima de 64 caracteres."
    }
})