trigger:
  batch: true
  branches:
    include:
    - main
    - dev
  paths:
    include:
    - SPFx/*
    - Azure/*
    exclude:
    - Azure/Infraestructure

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
    - template: ./jobs/job-build-artifacts-all.yaml