define([], function () {
  return {
    "HiMessage": "Hola",
    "Warning": "Avís",
    "WarningMessage": "Els canvis realitzats poden trigar uns minuts a reflectir-se.",
    "Phone": "Mòbil",
    "Email": "E-Mail",
    "Job": "Lloc",
    "Location": "Comunitat autònoma",
    'Alerts': 'Alerts',
    'ArchivedAlerts': 'Alerts arxivats',
    'AlertPhrase1': 'Tens',
    'AlertPhrase2': 'avís pendent',
    'AlertPhrase3': 'Alerts pendents',
    'AlertPhrase4': 'veure tots els Alerts',
    'ArchiveReadAlerts': 'Arxivar els Alerts llegits',
    'ViewArchivedAlerts': 'Veure els Alerts arxivats',
    'NoCurrentAlertsToShow': 'No hi ha Alerts per mostrar.',
    'NoArchivedAlertsToShow': 'No hi ha Alerts arxivats per mostrar.',
    'PersonalConfig': 'Configuració personal',
    'Discard': 'Descartar',
    'Save': 'Desa',
    'HideReaded': 'Amagar els Alerts llegits',
    'AValidEmailIsRequired': 'Heu d\'introduir un email vàlid (format: usuari@domini.extensió).',
    'AValidPhoneNumberIsRequired': 'Heu d\'introduir un número de telèfon vàlid (9 dígits consecutius, sense espais ni altres caràcters).',
    'Saving': 'Guardant',
    'BackendErrorMessage': 'S\'ha prodduït un error, torneu-ho a prodvar més tard.',
    'BasicData': 'Dades bàsiques',
    'NewTitle': 'Títol',
    'NewLocation': 'Ubicació',
    'NewLocationInformation': 'Detall de la ubicació',
    'NewMeetingType': 'Tipus de reunió',
    'NewDescription': 'Descripció',
    'NewStartDate': 'Data d\'inici',
    'NewEndDate': 'Data de fi',
    'NewOnlineTool': 'Eina online',
    'NewOnlineToolUrl': 'Url de l\'eina online',
    'TheOrderOfTheDayHasBeenUpdated': 'S\'ha actualitzat l\'ordre del dia.',
    'AddedAssistants': 'Assistents afegits',
    'RemovedAssistants': 'Assistents eliminats',
    'MeetingPoints': 'Ordre del dia',
    'Documents': 'Documents',
    'Agreements': 'Acords',
    'Minutes': 'Minutes',
    'TheMinutesHasBeenUpdated': 'L\'Minutes s\'ha actualitzat.',
    'SeeMore': 'Veure més',
    'SeeLess': 'Veure menys',
    'GoToTheMeeting': 'Anar a la convocatòria',
    'LoadingArchivedAlerts': 'Carregant els Alerts arxivats',
    'GetNotificationsFromThisSite':'Obté Notifications de tots els llocs',
    "FirstNameTooltip": "Nom de l'usuari",
    "LastNameTooltip": "Cognoms de l'usuari",
    "PhoneTooltip": "Número de telèfon",
    "PrincipalMailTooltip": "Correu electrònic principal",
    "OtherMailTooltip": "Correu electrònic alternatiu",
    "JobTitleTooltip": "Lloc",
    "OfficeLocationTooltip": "Comunitat autònoma",
  }
});