define([], function () {
  return {
    "HiMessage": "Hello",
    "Warning": "Warning",
    "WarningMessage": "Changes made may take a few minutes to be reflected.",
    "Phone": "Phone",
    "Email": "E-Mail",
    "Job": "Job",
    "Location": "Autonomous community",
    'Alerts': 'Alerts',
    'ArchivedAlerts': 'Archived alerts',
    'AlertPhrase1': 'You have',
    'AlertPhrase2': 'pending alert',
    'AlertPhrase3': 'pending alerts',
    'AlertPhrase4': 'see all alerts',
    'ArchiveReadAlerts': 'Archive read alerts',
    'ViewArchivedAlerts': 'View archived alerts',
    'NoCurrentAlertsToShow': 'There are no alerts to show.',
    'NoArchivedAlertsToShow': 'There are no archived alerts to show.',
    'PersonalConfig': 'Personal settings',
    'Discard': 'Discard',
    'Save': 'Save',
    'HideReaded': 'Hide read notifications',
    'AValidEmailIsRequired': 'You must enter a valid email (format: user@domain.extension).',
    'AValidPhoneNumberIsRequired': 'You must enter a valid phone number (9 consecutive digits, no spaces or other characters).',
    'Saving': 'Saving',
    'BackendErrorMessage': 'An error occurred, please try again later.',
    'BasicData': 'Basic data',
    'NewTitle': 'Title',
    'NewLocation': 'Location',
    'NewLocationInformation': 'Location detail',
    'NewMeetingType': 'Meeting type',
    'NewDescription': 'Description',
    'NewStartDate': 'Start date',
    'NewEndDate': 'End date',
    'NewOnlineTool': 'Online tool',
    'NewOnlineToolUrl': 'Online tool url',
    'TheOrderOfTheDayHasBeenUpdated': 'The order of the day has been updated.',
    'AddedAssistants': 'Added assistants',
    'RemovedAssistants': 'Removed assistants',
    'MeetingPoints': 'Order of the day',
    'Documents': 'Documents',
    'Agreements': 'Agreements',
    'Minutes': 'Minutes',
    'TheMinutesHasBeenUpdated': 'The minutes have been updated.',
    'SeeMore': 'See more',
    'SeeLess': 'See less',
    'GoToTheMeeting': 'Go to the meeting',
    'LoadingArchivedAlerts': 'Loading archived alerts',
    "FirstNameTooltip": "First name",
    "LastNameTooltip": "Last name",
    "PhoneTooltip": "Phone number",
    "PrincipalMailTooltip": "Primary email",
    "OtherMailTooltip": "Alternate email",
    "JobTitleTooltip": "Job title",
    "OfficeLocationTooltip": "Autonomous community"
  }
});