define([], function () {
  return {
    "HiMessage": "Hola",
    "Warning": "Alert",
    "WarningMessage": "Los cambios realizados pueden tardar unos minutos en reflejarse.",
    "Phone": "Móvil",
    "Email": "E-Mail",
    "Job": "Cargo",
    "Location": "Comunidad autónoma",
    'Alerts': 'Alerts',
    'ArchivedAlerts': 'Alerts archivados',
    'AlertPhrase1': 'Tienes',
    'AlertPhrase2': 'Alert pendiente',
    'AlertPhrase3': 'Alerts pendientes',
    'AlertPhrase4': 'ver todos los Alerts',
    'ArchiveReadAlerts': 'Archivar los Alerts leídos',
    'ViewArchivedAlerts': 'Ver los Alerts archivados',
    'NoCurrentAlertsToShow': 'No hay Alerts para mostrar.',
    'NoArchivedAlertsToShow': 'No hay Alerts archivados para mostrar.',
    'PersonalConfig': 'Configuración personal',
    'Discard': 'Descartar',
    'Save': 'Guardar',
    'HideReaded': 'Ocultar los Alerts leídos',
    'AValidEmailIsRequired': 'Debe introducir un email válido (formato: usuario@dominio.extensión).',
    'AValidPhoneNumberIsRequired': 'Debe introducir un número de teléfono válido (9 dígitos consecutivos, sin espacios ni otros caracteres).',
    'Saving': 'Guardando',
    'BackendErrorMessage': 'Se ha prodducido un error, vuelva a intentarlo más tarde.',
    'BasicData': 'Datos básicos',
    'NewTitle': 'Título',
    'NewLocation': 'Ubicación',
    'NewLocationInformation': 'Detalle de la ubicación',
    'NewMeetingType': 'Tipo de reunión',
    'NewDescription': 'Descripción',
    'NewStartDate': 'Fecha de inicio',
    'NewEndDate': 'Fecha de fin',
    'NewOnlineTool': 'Herramienta online',
    'NewOnlineToolUrl': 'Url de la herramienta online',
    'TheOrderOfTheDayHasBeenUpdated': 'Se ha actualizado el orden del día.',
    'AddedAssistants': 'Asistentes añadidos',
    'RemovedAssistants': 'Asistentes eliminados',
    'MeetingPoints': 'Orden del día',
    'Documents': 'Documents',
    'Agreements': 'Acuerdos',
    'Minutes': 'Minutes',
    'TheMinutesHasBeenUpdated': 'Se ha actualizado el Minutes.',
    'SeeMore': 'Ver más',
    'SeeLess': 'Ver menos',
    'GoToTheMeeting': 'Ir a la reunión',
    'LoadingArchivedAlerts': 'Cargando los Alerts archivados',
    'GetNotificationsFromThisSite':'Obtén Notifications de todos los sitios',
    "FirstNameTooltip": "Nombre",
    "LastNameTooltip": "Apellidos",
    "PhoneTooltip": "Número de teléfono",
    "PrincipalMailTooltip": "Correo electrónico principal",
    "OtherMailTooltip": "Correo electrónico alternativo",
    "JobTitleTooltip": "Cargo",
    "OfficeLocationTooltip": "Comunidad autónoma",
  }
});