define([], function () {
  return {
    "HiMessage": "Kaixo",
    "Warning": "Abisua",
    "WarningMessage": "Egindako aldaketak minutu batzuk behar izan ditzake islatzeko.",
    "Phone": "Mugikorra",
    "Email": "E-Mail",
    "Job": "Lanpostua",
    "Location": "Autonomia-erkidegoa",
    'Alerts': 'Jakinarazpenak',
    'ArchivedAlerts': 'Artxibatutako oharrak',
    'AlertPhrase1': 'Ohar',
    'AlertPhrase2': 'jakinarazpenaren zain',
    'AlertPhrase3': 'zain dauden oharrak',
    'AlertPhrase4': 'ikusi iragarki guztiak',
    'ArchiveReadAlerts': 'Artxiboa irakurri oharrak',
    'ViewArchivedAlerts': 'Ikusi artxibatutako oharrak',
    'NoCurrentAlertsToShow': 'Ez dago iragarkirik erakusteko.',
    'NoArchivedAlertsToShow': 'Ez dago iragarki artxibaturik bistaratzeko.',
    'PersonalConfig': 'Ezarpen pertsonalak',
    'Discard': 'Baztertu',
    'Save': 'Gorde',
    'HideReaded': 'Ezkutatu irakurritako oharrak',
    'AValidEmailIsRequired': 'Baliozko e-posta bat sartu behar duzu (formatua: erabiltzailea@domeinua.luzapena).',
    'AValidPhoneNumberIsRequired': 'Baliozko telefono-zenbaki bat sartu behar duzu (9 digitu jarraian, zuriunerik edo bestelako karaktererik gabe).',
    'Saving': 'Gordetzen',
    'BackendErrorMessage': 'Errore bat gertatu da, mesedez berriro saiatu geroago.',
    'BasicData': 'Oinarrizko datuak',
    'NewTitle': 'Izenburu',
    'NewLocation': 'Kokapen',
    'NewLocationInformation': 'Kokapenaren xehetasun',
    'NewMeetingType': 'Bilera mota',
    'NewDescription': 'Deskribapen',
    'NewStartDate': 'Hasteko data',
    'NewEndDate': 'Amaiera data',
    'NewOnlineTool': 'Sineko tresna',
    'NewOnlineToolUrl': 'Lineko tresnaren url',
    'TheOrderOfTheDayHasBeenUpdated': 'Eguneko ordena eguneratu da.',
    'AddedAssistants': 'Laguntzaileak gehitu',
    'RemovedAssistants': 'Laguntzaileak kendu',
    'MeetingPoints': 'Eguneko ordena',
    'Documents': 'Dokumentuak',
    'Agreements': 'Hitzarmenak',
    'Minutes': 'Aktak',
    'TheMinutesHasBeenUpdated': 'Aktak eguneratu dira.',
    'SeeMore': 'Gehiago ikusi',
    'SeeLess': 'Ikus gutxiago',
    'GoToTheMeeting': 'Joan deialdira',
    'LoadingArchivedAlerts': 'Artxibatutako jakinarazpenak kargatzen',
    'GetNotificationsFromThisSite':'Jaso gune guztietako jakinarazpenak',
    "FirstNameTooltip": "Erabiltzailearen izena",
    "LastNameTooltip": "Erabiltzailearen abizenak",
    "PhoneTooltip": "Telefono zenbakia",
    "PrincipalMailTooltip": "Posta elektroniko nagusia",
    "OtherMailTooltip": "Posta elektroniko alternatiboa",
    "JobTitleTooltip": "Kargua",
    "OfficeLocationTooltip": "Autonomia erkidegoa"
      }
});