define([], function () {
  return {
    "HiMessage": "Ola",
    "Warning": "Alert",
    "WarningMessage": "Os cambios realizados poden tardar uns minutos en reflectirse.",
    "Phone": "Móbil",
    "Email": "E-Mail",
    "Job": "Traballo",
    "Location": "Comunidade autónoma",
    'Alerts': 'Alerts',
    'ArchivedAlerts': 'Alerts arquivados',
    'AlertPhrase1': 'Tes',
    'AlertPhrase2': 'Alert pendente',
    'AlertPhrase3': 'Alerts pendentes',
    'AlertPhrase4': 'ver todos os Alerts',
    'ArchiveReadAlerts': 'Arquivar Alerts lidos',
    'ViewArchivedAlerts': 'Ver Alerts arquivados',
    'NoCurrentAlertsToShow': 'Non hai anuncios para mostrar.',
    'NoArchivedAlertsToShow': 'Non hai anuncios arquivados para mostrar.',
    'PersonalConfig': 'Configuración persoal',
    'Discard': 'Descartar',
    'Save': 'Manteña',
    'HideReaded': 'Ocultar Alerts lidos',
    'AValidEmailIsRequired': 'Debes introducir un email válido (formato: usuario@dominio.extensión).',
    'AValidPhoneNumberIsRequired': 'Debes introducir un número de teléfono válido (9 díxitos consecutivos, sen espazos nin outros caracteres).',
    'Saving': 'Gardando',
    'BackendErrorMessage': 'prodduciuse un erro, téntao de novo máis tarde.',
    'BasicData': 'Datos básicos',
    'NewTitle': 'Título',
    'NewLocation': 'Localización',
    'NewLocationInformation': 'Detalle da localización',
    'NewMeetingType': 'Tipo de reunión',
    'NewDescription': 'Descrición',
    'NewStartDate': 'Data de inicio',
    'NewEndDate': 'Data de finalización',
    'NewOnlineTool': 'Ferramenta en liña',
    'NewOnlineToolUrl': 'Url da ferramenta en liña',
    'TheOrderOfTheDayHasBeenUpdated': 'A orde do día foi actualizada.',
    'AddedAssistants': 'Asistentes engadidos',
    'RemovedAssistants': 'Asistentes eliminados',
    'MeetingPoints': 'Orde do día',
    'Documents': 'Documents',
    'Agreements': 'Acordos',
    'Minutes': 'Minutes',
    'TheMinutesHasBeenUpdated': 'Actualizáronse as Minutes.',
    'SeeMore': 'Ver máis',
    'SeeLess': 'Ver menos',
    'GoToTheMeeting': 'Vaia á Meeting',
    'LoadingArchivedAlerts': 'Cargando Alerts arquivados',
    'GetNotificationsFromThisSite':'Recibe notificacións de todos os sitios',
    "FirstNameTooltip": "Nome do usuario",
    "LastNameTooltip": "Apelidos do usuario",
    "PhoneTooltip": "Número de teléfono",
    "PrincipalMailTooltip": "Correo electrónico principal",
    "OtherMailTooltip": "Correo electrónico alternativo",
    "JobTitleTooltip": "Cargo",
    "OfficeLocationTooltip": "Comunidade autónoma"
  }
});