define([], function() {
  return {
    //Pane
    "propertyPaneDescription": "Administració",
    "BasicGroupName": "prodpietats",
    "NoResultsFoundPicker": "No s'han trobat resultats",
    "LoadingPicker": "Carregant...",
    "TitlePane": "Títol",
    "ComponentTypePane": "Tipus d'administració",
    "ItemsPerPage": "Elements per pàgina",
    "ShowEXTERNAL": "Mostrar òrgans de EXTERNAL",

    //AdministrationApp
    "ManageOrgan": "Gestió d'un òrgan",
    "ManageUser": "Gestió d'un usuari",
    "LoadingLabel": "Carregant informació...",
    "LoadingError": "No s' ha pogut obtenir la informació. Intèrtestt de nou més tard.",
    "NewOrgan": "Nou òrgan",
    "NewUser": "Nou usuari",

    //SearchBar
    "SearchTypePlaceholder": "Tipus de cerca",
    "OrgansType": "Òrgans",
    "UsersType": "Usuaris",
    "SearchPlaceholder": "Introdueix el text de cerca",
    "SearchLabel": "Cerca",
    "CleanSearch": "Neteja la cerca",

    //FilterZone
    "SelectValue": "Selecciona un valor",
    "OrganTypeFilter": "Tipus d'òrgan",
    "OrganTypeFilterPlaceholder": "Selecciona un tipus",
    "UserFilter": "Usuari",
    "UserFilterPlaceholder": "Selecciona un usuari",
    "OrganFilter": "Òrgan",
    "OrganFilterPlaceholder": "Selecciona un òrgan",
    "CCAAFilter": "Comunitat Autònoma",
    "CCAAFilterPlaceholder": "Selecciona una comunitat",
    "RoleFilter": "Rol",
    "RoleFilterPlaceholder": "Selecciona un rol",
    "LicenseFilter": "Llicència",
    "LicenseFilterPlaceholder": "Selecciona si té llicència",
    "LicenseYes": "Sí",
    "LicenseNo": "No",
    "BusinessAreaFilter": "Àrea sectorial",
    "BusinessAreaPlaceholder": "Selecciona una àrea",

    //ResultZone
    "NameHeader": "Nom",
    "NomenclaturaHeader": "Nomenclatura",
    "TypeHeader": "Tipus",
    "MailHeader": "Correu electrònic",
    "OrgansHeader": "Òrgans",
    "ManageLabel": "Gestionar",
    "NoResults": "No s'han trobat resultats",
    "PageNumberTxt": "Pàgina",
    "FromTotalPageTxt": "de",
    "CertificateLabel": "Certificat",

    "Users": "Usuaris",
      "Organs": "Òrgans",
      "properties": "prodpietats",
      "List": "Llistat",
      "Templates": "Plantilles",
      
      // prodPIETATS ÒRGAN
      "DepartmentName": "Nom de l'òrgan",
      "DepartmentNamePlaceholder": "Selecciona un òrgan",
      "OrganType": "Tipus d'òrgan",
      "GeneralPlaceholder": "Seleccioneu un valor",
      "Ministry": "Ministeri",
      "Nomenclature": "Nomenclatura",
      "Secretaria": "Secretaria",
      "Intersectorial": "Intersectorial",
      "BusinessArea": "Àrea sectorial",
      "Subject":"Matèria",
      "Abbreviation": "Abreviatura",
      "Legislature": "Period",
      "CreationDate": "Data de constitució",
      "ExpirationDate": "Data d'extinció",
      "DaysToApprodve": "Dies per aprodvar l'Minutes",
      "SIA": "SIA",
      "DIR3": "DIR3",
      "Description": "Descripció",
      "Observations": "Observacions",
      "ActiveStatus": "Estat",
      "ActiveYes": "Actiu",
      "ActiveNo": "Inactiu",
      "IntersectorialYes": "Sí",
      "IntersectorialNo": "No",
      "DepartmentNameExist": "Ja existeix un altre òrgan amb aquest nom.",
      "CodigoDepartment": "Codi òrgan",
      "FechaInscripcion": "Data d'inscripció",
      "StatusDepartment": "Situació",
      "DepartmentAdscripcion": "Órgano de adscripción",
      "Inscrito": "Inscrito",
      "YesLabel": "Sí",
      "NoLabel": "No",
      // prodPIETATS USUARI
      "Name": "Nom",
      "SurName": "Cognoms",
      "DisplayName": "Nom per mostrar",
      "Email": "Correu electrònic",
      "SecondaryMail": "Correu electrònic secundari",
      "PhoneNumber": "Telèfon mòbil",
      "Job": "Càrrec",
      "AutonomousCommunity": "Comunitat autònoma",
      "FieldRequired":"Aquest camp és obligatori.",
      "PhoneError":"Has d’introduir un número de telèfon vàlid (9 dígits consecutius, sense espais ni altres caràcters).",
      "MailError":"Has d’introduir un correu electrònic vàlid (format: usuari@domini.extensió).",

      // LLISTAT USUARIS / ÒRGANS
      "Members": "Membres",
      "Role": "Rols",
      "Remove": "Eliminar",
      "AddNewUser": "Afegir usuari",
      "AddNewOrgan": "Afegir òrgan",
      "SelectUserPlaceholder": "Selecciona un usuari",
      "SelectOrganPlaceholder": "Selecciona un òrgan",
      "SelectRolePlaceholder": "Selecciona un rol",
      "SelectCCAAPlaceholder": "Selecciona una comunidad",
      "NeedLicense": "L'usuari tindrà funcionalitat limitada si no disposa de llicència",
      "SavingLoading": "Actualitzant la informació",

      "ChangesDone": "Es faran els següents canvis:",
      "AreYouSure": "Estàs segur de fer aquests canvis?",
      "NoChanges": "No s'han fet canvis",
      "ECNTyValueChange":"(buit)",
      "RemovedListItem": "Eliminat",
      "ErrorListOrgan": "Hi ha usuaris duplicats, revisa els canvis abans de desar.",
      "ErrorListUser": "Hi ha òrgans duplicats, revisa els canvis abans de desar.",
      "UserDuplicated": "Ja hi ha una entrada per a aquest usuari en l'òrgan.",
      "OrganDuplicated": "Ja hi ha una entrada per a aquest òrgan en l'usuari.",
      "CheckPermissionsTooltip": "Comprodva si els permisos de l'usuari s'han aplicat correctament",
      "UserLabel": "Usuari",
      "OrganLabel": "Òrgan",
      "RoleLabel": "Rol",
      "CheckPermissionsLabel": "Comprodvació de permisos",
      "UserHasPermissionsTxt": "L'usuari té permisos en el rol indicat",
      "UserNotPermissionsTxt": "L'usuari encara no disposa dels permisos en el rol indicat",
      "Accept": "Acceptar",
      "PermissionsTimeNote": "Aquests canvis poden trigar diversos minuts a fer-se efectius.",
      "Warning": "Avís",
      "WarningMessage": "Els canvis realitzats poden trigar uns minuts a reflectir-se.",
      "WarningNameChange": "* El canvi de nom pot trigar uns minuts a aplicar-se",
      "FechaCreacion": "Data creació",
      "DesdeFilter": "Des de",
      "HastaFilter": "Fins a",
      "DocumentsTooltip": "Documents",
      
      "ErrorMsg": "S’ha prodduït un error, intenta-ho més tard.",
      "Save": "Desar",
      "Discard": "Descartar",
      "DuplicatedCode": "Ja existeix un altre òrgan amb aquest codi.",
     
      "UploadDocument": "Pujar document",
      "FileRequired": "Has de pujar un fitxer.",
      "TipoDepartmentRequired": "El tipus d'òrgan és obligatori.",
      "TipoDocumentRequired": "El tipus de document és obligatori.",
      "DepartmentRequired": "L'òrgan és obligatori.",
      "SelectFolderRequired": "Has de seleccionar una carpeta o marcar 'Nova carpeta' per crear-ne una nova.",
      "NewFolderRequired": "Has d'indicar el nom de la nova carpeta.",
      "FolderDuplicated": "Ja existeix una carpeta amb aquest nom.",
      "FileLabel": "Fitxer",
      "DocumentTypeLabel": "Tipus de document",
      "DocumentTypePlaceHolder": "Selecciona un tipus de document",
      "FechaMeetingLabel": "Data de convocatòria",
      "CarpetaReunionLabel": "Carpeta de la reunió",
      "SelectFolderPlaceholder": "Selecciona la carpeta",
      "CreateNewFolder": "Crear nova carpeta?",
      "NewFolderName": "Nom de la nova carpeta",
      "SavedOk": "S'ha desat correctament.",
      "SavingLoad": "Desant...",
      "Close": "Tancar",
      "Cancel": "Cancel·lar"
  };
});