define([], function() {
  return {
    //Pane
    "propertyPaneDescription": "Administration",
    "BasicGroupName": "properties",
    "NoResultsFoundPicker": "No results found",
    "LoadingPicker": "Loading...",
    "TitlePane": "Title",
    "ComponentTypePane": "Administration Type",
    "ItemsPerPage": "Items per page",
    "ShowEXTERNAL": "Show EXTERNAL organs",

    //AdministrationApp
    "ManageOrgan": "Manage an organ",
    "ManageUser": "Manage a user",
    "LoadingLabel": "Loading information...",
    "LoadingError": "The information could not be obtained. Please try again later.",
    "NewOrgan": "Nou òrgan",
    "NewUser": "Nou usuari",  

    //SearchBar
    "SearchTypePlaceholder": "Search type",
    "OrgansType": "Organs",
    "UsersType": "Users",
    "SearchPlaceholder": "Enter search text",
    "SearchLabel": "Search",
    "CleanSearch": "Clear search",

    //FilterZone
    "SelectValue": "Select a value",
    "OrganTypeFilter": "Organ type",
    "OrganTypeFilterPlaceholder": "Select a type",
    "UserFilter": "User",
    "UserFilterPlaceholder": "Select a user",
    "OrganFilter": "Organ",
    "OrganFilterPlaceholder": "Select an organ",
    "CCAAFilter": "Autonomous Community",
    "CCAAFilterPlaceholder": "Select a community",
    "RoleFilter": "Role",
    "RoleFilterPlaceholder": "Select a role",
    "LicenseFilter": "License",
    "LicenseFilterPlaceholder": "Select a value",
    "LicenseYes": "Yes",
    "LicenseNo": "No",
    "BusinessAreaFilter": "Sectorial area",
    "BusinessAreaPlaceholder": "Select an area",
    
    //ResultZone
    "NameHeader": "Name",
    "NomenclaturaHeader": "Nomenclature",
    "TypeHeader": "Type",
    "MailHeader": "Email",
    "OrgansHeader": "Organs",
    "ManageLabel": "Manage",
    "NoResults": "No results found",
    "PageNumberTxt": "Page",
    "FromTotalPageTxt": "from",
    "CertificateLabel": "Certificate",


    "Users": "Users",
      "Organs": "Organs",
      "properties": "properties",
      "List": "List",
      "Templates": "Templates",
      
      // ORGAN prodPERTIES
      "DepartmentName": "Organ Name",
      "DepartmentNamePlaceholder": "Select an organ",
      "OrganType": "Organ Type",
      "GeneralPlaceholder": "Select a value",
      "Ministry": "Ministry",
      "Nomenclature": "Nomenclature",
      "Secretaria": "Secretariat",
      "Intersectorial": "Intersectorial",
      "BusinessArea": "Sectorial area",
      "Subject":"Subject",
      "Abbreviation": "Abbreviation",
      "Legislature": "Legislature",
      "CreationDate": "Creation Date",
      "ExpirationDate": "Expiration Date",
      "DaysToApprodve": "Days to approdve the minutes",
      "SIA": "SIA",
      "DIR3": "DIR3",
      "Description": "Description",
      "Observations": "Observations",
      "ActiveStatus": "Status",
      "ActiveYes": "Active",
      "ActiveNo": "Inactive",
      "IntersectorialYes": "Yes",
      "IntersectorialNo": "No",
      "SelectOrgan":"Selecciona un término existente",
      "CreateNewOrgan":"Crea un nuevo término",
      "DepartmentNameExist": "Another organ with this name already exists.",
      "CodigoDepartment": "Organ code",
      "FechaInscripcion": "Registration date",
      "StatusDepartment": "Situation",
      "DepartmentAdscripcion": "Órgano de adscripción",
      "Inscrito": "Inscrito",
      "YesLabel": "Sí",
      "NoLabel": "No",
      // USER prodPERTIES
      "Name": "Name",
      "SurName": "Surname",
      "DisplayName": "Display Name",
      "Email": "Email",
      "SecondaryMail": "Secondary Email",
      "PhoneNumber": "Mobile Phone",
      "Job": "Job",
      "AutonomousCommunity": "Autonomous Community",
      "FieldRequired":"This field is required.",
      "PhoneError":"You must enter a valid phone number (9 consecutive digits, without spaces or other characters).",
      "MailError":"You must enter a valid email (format: user@domain.extension).",

      // USER / ORGAN LIST
      "Members": "Members",
      "Role": "Roles",
      "Remove": "Remove",
      "AddNewUser": "Add User",
      "AddNewOrgan": "Add Organ",
      "SelectUserPlaceholder": "Select a user",
      "SelectOrganPlaceholder": "Select an organ",
      "SelectRolePlaceholder": "Select a role",
      "SelectCCAAPlaceholder": "Select a community",
      "NeedLicense": "The user will have limited functionality without a license",
      
      "ChangesDone": "The following changes will be made:",
      "AreYouSure": "Are you sure you want to make these changes?",
      "NoChanges": "No changes have been made",
      "ECNTyValueChange":"(eCNTy)",
      "SavingLoading": "Updating information",
      "RemovedListItem": "Removed",
      "ErrorListOrgan": "There are duplicate users, review the changes before saving.",
      "ErrorListUser": "There are duplicate organs, review the changes before saving.",
      "UserDuplicated": "There is already an entry for this user in the organ.",
      "OrganDuplicated": "There is already an entry for this organ in the user.",
      "CheckPermissionsTooltip": "Check if the user's permissions have been applied correctly",
      "UserLabel": "User",
      "OrganLabel": "Organ",
      "RoleLabel": "Role",
      "CheckPermissionsLabel": "Permissions check",
      "UserHasPermissionsTxt": "The user has permissions for the specified role",
      "UserNotPermissionsTxt": "The user does not yet have permissions for the specified role",
      "Accept": "Accept",
      "PermissionsTimeNote": "These changes may take several minutes to take effect.",
      "Warning": "Warning",
      "WarningMessage": "Changes made may take a few minutes to be reflected.",
      "WarningNameChange": "* The name change may take a few minutes to apply",
      "FechaCreacion": "Creation date",
      "DesdeFilter": "From",
      "HastaFilter": "Until",
      "DocumentsTooltip": "Documents",

      "ErrorMsg": "An error has occurred, please try again later.",
      "Save": "Save",
      "Discard": "Discard",
      "DuplicatedCode": "Another organ with this code already exists.",

      "UploadDocument": "Upload document",
      "FileRequired": "You must upload a file.",
      "TipoDepartmentRequired": "Organ type is required.",
      "TipoDocumentRequired": "Document type is required.",
      "DepartmentRequired": "Organ is required.",
      "SelectFolderRequired": "You must select a folder or check 'New folder' to create a new one.",
      "NewFolderRequired": "You must provide the name of the new folder.",
      "FolderDuplicated": "A folder with this name already exists.",
      "FileLabel": "File",
      "DocumentTypeLabel": "Document type",
      "DocumentTypePlaceHolder": "Select a document type",
      "FechaMeetingLabel": "Meeting date",
      "CarpetaReunionLabel": "Meeting folder",
      "SelectFolderPlaceholder": "Select the folder",
      "CreateNewFolder": "Create new folder?",
      "NewFolderName": "New folder name",
      "SavedOk": "Saved successfully.",
      "SavingLoad": "Saving...",
      "Close": "Close",
      "Cancel": "Cancel"
  };
});