define([], function() {
  return {
    //Pane
  "propertyPaneDescription": "Administracion",
  "BasicGroupName": "prodpiedades",
  "NoResultsFoundPicker":"No se han encontrado resultados",
  "LoadingPicker":"Cargando...",
  "TitlePane":"Título",
  "ComponentTypePane":"Tipo de Administración",
  "ItemsPerPage":"Elementos por página",
  "ShowEXTERNAL": "Mostrar órganos de EXTERNAL",

  //AdministrationApp
  "ManageOrgan":"Información del órgano",
  "ManageUser":"Gestión de un usuario",
  "LoadingLabel": "Cargando información...",
  "LoadingError": "No se ha podido obtener la información. Inténtelo de nuevo más tarde.",
  "NewOrgan":"Nuevo órgano",
  "NewUser":"Nuevo usuario",

  //SearchBar
  "SearchTypePlaceholder":"Tipo de búsqueda",
  "OrgansType":"Órganos",
  "UsersType":"Usuarios",
  "SearchPlaceholder":"Introduce el texto de búsqueda",
  "SearchLabel":"Buscar",
  "CleanSearch":"Limpiar búsqueda",

  //FilterZone
  "SelectValue":"Selecciona un valor",
  "OrganTypeFilter":"Tipo de órgano",
  "OrganTypeFilterPlaceholder":"Selecciona un tipo",
  "UserFilter":"Usuario",
  "UserFilterPlaceholder":"Introduce un usuario",
  "OrganFilter":"Órgano",
  "OrganFilterPlaceholder":"Selecciona un órgano",
  "CCAAFilter":"Comunidad Autónoma",
  "CCAAFilterPlaceholder":"Selecciona una comunidad",
  "RoleFilter":"Rol",
  "RoleFilterPlaceholder":"Selecciona un rol",
  "LicenseFilter":"Licencia",
  "LicenseFilterPlaceholder":"Selecciona si tiene licencia",
  "LicenseYes":"Sí",
  "LicenseNo":"No",
  "BusinessAreaFilter":"Área sectorial",
  "BusinessAreaPlaceholder":"Selecciona un área",
  "ApplyFilter":"Aplicar filtro",
  "RemoveFilter":"Borrar filtro",

  //ResultZone
  "NameHeader":"Nombre",
  "NomenclaturaHeader":"Nomenclatura",
  "TypeHeader":"Tipo",
  "MailHeader":"Correo electrónico",
  "OrgansHeader":"Órganos",
  "ManageLabel":"Gestionar",
  "CertificateLabel": "Certificado",
  "NoResults":"No se han encontrado resultados",
  "PageNumberTxt":"Página",
  "FromTotalPageTxt":"de",


  "Users":"Usuarios",
  "Organs": "Departments",
  "properties":"prodpiedades",
  "List":"Listado",
  "Templates":"Plantillas",
  
  //prodPIEDADES Department
  "DepartmentName":"Nombre del órgano",
  "DepartmentNamePlaceholder":"Selecciona un órgano",
  "OrganType":"Tipo de órgano",
  "GeneralPlaceholder":"Seleccione un valor",
  "Ministry":"Division",
  "Nomenclature":"Nomenclatura",
  "Secretaria": "Secretaría",
  "Intersectorial":"Intersectorial",
  "Subject":"Materia",
  "BusinessArea":"Área sectorial",
  "Abbreviation":"Abreviatura",
  "Legislature":"Period",
  "CreationDate":"Fecha constitución",
  "ExpirationDate":"Fecha extinción",
  "DaysToApprodve":"Días para aprodbar el Minutes",
  "SIA":"SIA",
  "DIR3":"DIR3",
  "Description":"Descripción",
  "Observations":"Observaciones",
  "ActiveStatus": "Estado",
  "ActiveYes": "Activo",
  "ActiveNo":"Inactivo",
  "IntersectorialYes":"Sí",
  "IntersectorialNo":"No",
  "SelectOrgan":"Selecciona un término existente",
  "CreateNewOrgan":"Crea un nuevo término",
  "DepartmentNameExist": "Ya existe otro órgano con este nombre.",
  "CodigoDepartment": "Código órgano",
  "FechaInscripcion": "Fecha inscripción",
  "StatusDepartment": "Situación",
  "DepartmentAdscripcion": "Órgano de adscripción",
  "Inscrito": "Inscrito",
  "YesLabel": "Sí",
  "NoLabel": "No",

  //prodPIEDADES USUARIO
  "Name":"Nombre",
  "SurName":"Apellidos",
  "DisplayName":"Nombre para mostrar",
  "Email": "Correo electrónico",
  "SecondaryMail":"Correo electrónico secundario",
  "PhoneNumber":"Teléfono móvil",
  "Job":"Cargo",
  "AutonomousCommunity":"Comunidad autónoma",

  "FieldRequired":"Este campo es obligatorio.",
  "PhoneError":"Debe introducir un número de teléfono válido (9 dígitos consecutivos, sin espacios ni otros caracteres).",
  "MailError":"Debe introducir un email válido (formato: usuario@dominio.extensión).",

  //LISTADO USUARIOS / Departments
  "Members":"members",
  "Role":"Roles",
  "Remove":"Eliminar",
  "AddNewUser":"Añadir usuario",
  "AddNewOrgan":"Añadir órgano",
  "SelectUserPlaceholder":"Introduce un usuario",
  "SelectOrganPlaceholder": "Selecciona un órgano",
  "SelectRolePlaceholder": "Selecciona un rol",
  "SelectCCAAPlaceholder": "Selecciona una comunidad",
  "SavingLoading": "Actualizando la información",

  "ChangesDone":"Se van a realizar los siguientes cambios:",
  "AreYouSure": "¿Estás seguro de realizar estos cambios?",
  "NoChanges": "No se han realizado cambios",
  "ECNTyValueChange":"(vacío)",
  "RemovedListItem": "Eliminado",
  "NeedLicense": "El usuario tendrá funcionalidad limitada al no disponer de licencia",
  "ErrorListOrgan":"Hay usuarios duplicados, revisa los cambios antes de guardar.",
  "ErrorListUser":"Hay órganos duplicados, revisa los cambios antes de guardar.",
  "UserDuplicated":"Ya hay una entrada para este usuario en el órgano.",
  "OrganDuplicated":"Ya hay una entrada para este órgano en el usuario.",
  "CheckPermissionsTooltip": "Comprueba si los permisos del usuario ya se han aplicado correctamente",
  "UserLabel": "Usuario",
  "OrganLabel": "Órgano",
  "RoleLabel": "Rol",
  "CheckPermissionsLabel": "Comprodbación de permisos",
  "UserHasPermissionsTxt": "El usuario tiene permisos en el rol indicado",
  "UserNotPermissionsTxt": "El usuario aún no dispone de los permisos en el rol indicado",
  "Accept": "Aceptar",
  "PermissionsTimeNote": "Estos cambios pueden tardar varios minutos en hacerse efectivos.",
  "Warning": "Alert",
  "WarningMessage": "Los cambios realizados pueden tardar unos minutos en reflejarse.",
  "WarningNameChange": "* El cambio de nombre puede tardar unos minutos en aplicarse",

  "FechaCreacion": "Fecha creación",
  "DesdeFilter": "Desde",
  "HastaFilter": "Hasta",
  "DocumentsTooltip": "Documents",
  
  "ErrorMsg": "Ha ocurrido un error, intentelo más tarde.",
  "Save":"Guardar",
  "Discard":"Descartar",
  "DuplicatedCode": "Ya existe un órgano con este código",

  "UploadDocument": "Subir Document",
  "FileRequired": "Debe subir un archivo.",
  "TipoDepartmentRequired": "Tipo de órgano es obligatorio.",
  "TipoDocumentRequired": "Tipo de Document es obligatorio.",
  "DepartmentRequired": "Órgano es obligatorio.",
  "SelectFolderRequired": "Debe seleccionar una carpeta o marcar 'Nueva carpeta' para crear una nueva.",
  "NewFolderRequired": "Debe indicar el nombre de la nueva carpeta.",
  "FolderDuplicated": "Ya existe una carpeta con este nombre.",
  "FileLabel" : "Archivo",
  "DocumentTypeLabel": "Tipo de Document",
  "DocumentTypePlaceHolder": "Selecciona un tipo de Document",
  "FechaMeetingLabel": "Fecha Meeting",
  "CarpetaReunionLabel": "Carpeta de la reunión",
  "SelectFolderPlaceholder": "Selecciona la carpeta",
  "CreateNewFolder": "¿Crear nueva carpeta?",
  "NewFolderName": "Nombre de la nueva carpeta",
  "SavedOk": "Se ha guardado correctamente.",
  "SavingLoad": "Guardando...",
  "Close": "Cerrar",
  "Cancel": "Cancelar"
  }
})