define([], function() {
  return {
    //Pane
    "propertyPaneDescription": "Administrazioa",
    "BasicGroupName": "prodpietateak",
    "NoResultsFoundPicker": "Emaitzarik ez",
    "LoadingPicker": "Kargatzen...",
    "TitlePane": "Izenburua",
    "ComponentTypePane": "Administrazio mota",
    "ItemsPerPage": "Orriko elementuak",
    "ShowEXTERNAL": "EXTERNAL Departmentak erakutsi",

    //AdministrationApp
    "ManageOrgan": "Department bat kudeatu",
    "ManageUser": "Erabiltzaile bat kudeatu",
    "LoadingLabel": "Informazioa kargatzen...",
    "LoadingError": "Ezin izan da informazioa lortu. Saia zaitez berriro geroago.",
    "NewOrgan": "Department berria",
    "NewUser": "Erabiltzaile berria",

    //SearchBar
    "SearchTypePlaceholder": "Bilaketa mota",
    "OrgansType": "Departmentak",
    "UsersType": "Erabiltzaileak",
    "SearchPlaceholder": "Idatzi bilaketa testua",
    "SearchLabel": "Bilatu",
    "CleanSearch": "Garbitu bilaketa",

    //FilterZone
    "SelectValue": "Hautatu balio bat",
    "OrganTypeFilter": "Department mota",
    "OrganTypeFilterPlaceholder": "Hautatu mota bat",
    "UserFilter": "Erabiltzailea",
    "UserFilterPlaceholder": "Hautatu erabiltzaile bat",
    "OrganFilter": "Departmenta",
    "OrganFilterPlaceholder": "Hautatu Department bat",
    "CCAAFilter": "Autonomia Erkidegoa",
    "CCAAFilterPlaceholder": "Hautatu erkidego bat",
    "RoleFilter": "Rol",
    "RoleFilterPlaceholder": "Hautatu rol bat",
    "LicenseFilter": "Lizentzia",
    "LicenseFilterPlaceholder": "Hautatu lizentzia duen ala ez",
    "LicenseYes": "Bai",
    "LicenseNo": "Ez",
    "BusinessAreaFilter": "Arlo sektoriala",
    "BusinessAreaPlaceholder": "Aukeratu arlo bat",

    //ResultZone
    "NameHeader": "Izena",
    "NomenclaturaHeader": "Nomenklatura",
    "TypeHeader": "Mota",
    "MailHeader": "Posta elektronikoa",
    "OrgansHeader": "Departmentak",
    "ManageLabel": "Kudeatu",
    "NoResults": "Emaitzarik ez",
    "PageNumberTxt": "Orrialdea",
    "FromTotalPageTxt": "tik",
    "CertificateLabel": "Ziurtagiria",


    "Users": "Erabiltzaileak",
    "Organs": "Departmentak",
    "properties": "prodpietateak",
    "List": "Zerrenda",
    "Templates": "Txantiloiak",
    
    // DepartmentAREN prodPIETATEAK
    "DepartmentName": "Departmentaren izena",
    "DepartmentNamePlaceholder": "Hautatu Department bat",
    "OrganType": "Department mota",
    "GeneralPlaceholder": "Hautatu balio bat",
    "Ministry": "Divisiona",
    "Nomenclature": "Nomenklatura",
    "Secretaria": "Idazkaritza",
    "Intersectorial": "Sektore artekoa",
    "Subject": "Gaia",
    "BusinessArea": "Sektore arloa",
    "Abbreviation": "Laburdura",
    "Legislature": "Legegintzaldia",
    "CreationDate": "Sortze data",
    "ExpirationDate": "Amaiera data",
    "DaysToApprodve": "Aktak onartzeko egunak",
    "SIA": "SIA",
    "DIR3": "DIR3",
    "Description": "Deskribapena",
    "Observations": "Oharrak",
    "ActiveStatus": "Egoera",
    "ActiveYes": "Aktiboa",
    "ActiveNo": "Inaktiboa",
    "IntersectorialYes": "Bai",
    "IntersectorialNo": "Ez",
    "SelectOrgan":"Selecciona un término existente",
    "CreateNewOrgan":"Crea un nuevo término",
    "DepartmentNameExist": "Izen honekin beste Department bat dago jada.",
    "CodigoDepartment": "Department kodea",
    "FechaInscripcion": "Erregistro data",
    "StatusDepartment": "Egoera",
    "DepartmentAdscripcion": "Órgano de adscripción",
    "Inscrito": "Inscrito",
    "YesLabel": "Sí",
    "NoLabel": "No",
    // ERABILTZAILEAREN prodPIETATEAK
    "Name": "Izena",
    "SurName": "Abizenak",
    "DisplayName": "Erakutsi izena",
    "Email": "Posta elektronikoa",
    "SecondaryMail": "Bigarren posta elektronikoa",
    "PhoneNumber": "Telefono mugikorra",
    "Job": "Kargua",
    "AutonomousCommunity": "Autonomia erkidegoa",
    "FieldRequired":"Eremu hau derrigorrezkoa da.",
    "PhoneError":"Telefono zenbaki baliodun bat sartu behar duzu (9 zenbaki jarraian, espaziorik edo beste karaktererik gabe).",
    "MailError":"Baliozko email bat sartu behar duzu (formatua: erabiltzailea@domeinua.hedapena).",

    // ERABILTZAILEAK / DepartmentAK ZERRENDA
    "Members": "Kideak",
    "Role": "Rolak",
    "Remove": "Ezabatu",
    "AddNewUser": "Erabiltzailea gehitu",
    "AddNewOrgan": "Departmenta gehitu",
    "SelectUserPlaceholder": "Hautatu erabiltzaile bat",
    "SelectOrganPlaceholder": "Hautatu Department bat",
    "SelectRolePlaceholder": "Hautatu rol bat",
    "SelectCCAAPlaceholder": "Selecciona una comunidad", 
    
    "ChangesDone": "Hurrengo aldaketak egingo dira:",
    "AreYouSure": "Ziur zaude aldaketa hauek egin nahi dituzula?",
    "NoChanges": "Ez da aldaketarik egin",
    "ECNTyValueChange":"(hutsik)",
    "SavingLoading": "Informazioa eguneratzen",
    "RemovedListItem": "Ezabatua",
    "NeedLicense": "Erabiltzaileak funtzionalitate mugatua izango du lizentziarik gabe",
    "ErrorListOrgan": "Erabiltzaile bikoiztuak daude, berrikus aldaketak gorde aurretik.",
    "ErrorListUser": "Department bikoiztuak daude, berrikus aldaketak gorde aurretik.",
    "UserDuplicated": "Erabiltzaile honetarako sarrera bat dago Departmentan.",
    "OrganDuplicated": "Department honetarako sarrera bat dago erabiltzailean.",
    "CheckPermissionsTooltip": "Erabiltzailearen baimenak behar bezala aplikatu diren egiaztatu",
    "UserLabel": "Erabiltzailea",
    "OrganLabel": "Departmenta",
    "RoleLabel": "Rola",
    "CheckPermissionsLabel": "Baimenen egiaztapena",
    "UserHasPermissionsTxt": "Erabiltzaileak adierazitako rolaren baimenak ditu",
    "UserNotPermissionsTxt": "Erabiltzaileak oraindik ez ditu adierazitako rolaren baimenak",
    "Accept": "Onartu",
    "PermissionsTimeNote": "Aldaketa hauek hainbat minutu behar izan ditzakete eraginkorrak izateko.",
    "Warning": "Abisua",
    "WarningMessage": "Egindako aldaketak minutu batzuk behar izan ditzake islatzeko.",
    "Warning": "Abisua",
    "WarningMessage": "Egindako aldaketak minutu batzuk behar izan ditzake islatzeko.",
    "WarningNameChange": "* Izena aldatzeak minutu batzuk behar izan ditzake aplikatzeko",
    "FechaCreacion": "Sortze data",
    "DesdeFilter": "Noiztik",
    "HastaFilter": "Noiz arte",
    "DocumentsTooltip": "Dokumentuak",

    "ErrorMsg": "Errore bat gertatu da, saiatu geroago.",
    "Save": "Gorde",
    "Discard": "Baztertu",
    "DuplicatedCode": "Kodea honekin beste Department bat dago jada.",
    
    "UploadDocument": "Dokumentua igo",
    "FileRequired": "Fitxategi bat igo behar duzu.",
    "TipoDepartmentRequired": "Department mota derrigorrezkoa da.",
    "TipoDocumentRequired": "Dokumentu mota derrigorrezkoa da.",
    "DepartmentRequired": "Departmenta derrigorrezkoa da.",
    "SelectFolderRequired": "Karpetaren bat aukeratu edo 'Karpeta berria' markatu behar duzu berria sortzeko.",
    "NewFolderRequired": "Karpeta berriaren izena eman behar duzu.",
    "FolderDuplicated": "Izen hori duen karpeta bat badago dagoeneko.",
    "FileLabel": "Fitxategia",
    "DocumentTypeLabel": "Dokumentu mota",
    "DocumentTypePlaceHolder": "Aukeratu dokumentu mota bat",
    "FechaMeetingLabel": "Deialdiaren data",
    "CarpetaReunionLabel": "Bileraren karpeta",
    "SelectFolderPlaceholder": "Aukeratu karpeta",
    "CreateNewFolder": "Karpeta berria sortu?",
    "NewFolderName": "Karpeta berriaren izena",
    "SavedOk": "Ongi gorde da.",
    "SavingLoad": "Gordetzen...",
    "Close": "Itxi",
    "Cancel": "Utzi"
  };
});