define([], function() {
  return {
    //Pane
    "propertyPaneDescription": "Administración",
    "BasicGroupName": "prodpiedades",
    "NoResultsFoundPicker": "Non se atoparon resultados",
    "LoadingPicker": "Cargando...",
    "TitlePane": "Título",
    "ComponentTypePane": "Tipo de administración",
    "ItemsPerPage": "Elementos por páxina",
    "ShowEXTERNAL": "Mostrar órganos de EXTERNAL",

    //AdministrationApp
    "ManageOrgan": "Xestión dun órgano",
    "ManageUser": "Xestión dun usuario",
    "LoadingLabel": "Cargando información...",
    "LoadingError": "Non se puido obter a información. Inténtelo de novo máis tarde.",
    "NewOrgan": "Department berria",
    "NewUser": "Erabiltzaile berria",

    //SearchBar
    "SearchTypePlaceholder": "Tipo de busca",
    "OrgansType": "Órganos",
    "UsersType": "Usuarios",
    "SearchPlaceholder": "Introduce o texto de busca",
    "SearchLabel": "Buscar",
    "CleanSearch": "Limpar busca",

    //FilterZone
    "SelectValue": "Selecciona un valor",
    "OrganTypeFilter": "Tipo de órgano",
    "OrganTypeFilterPlaceholder": "Selecciona un tipo",
    "UserFilter": "Usuario",
    "UserFilterPlaceholder": "Selecciona un usuario",
    "OrganFilter": "Órgano",
    "OrganFilterPlaceholder": "Selecciona un órgano",
    "CCAAFilter": "Comunidade Autónoma",
    "CCAAFilterPlaceholder": "Selecciona unha comunidade",
    "RoleFilter": "Rol",
    "RoleFilterPlaceholder": "Selecciona un rol",
    "LicenseFilter": "Licenza",
    "LicenseFilterPlaceholder": "Selecciona se ten licenza",
    "LicenseYes": "Si",
    "LicenseNo": "Non",
    "BusinessAreaFilter": "Área sectorial",
    "BusinessAreaPlaceholder": "Selecciona unha área",

    //ResultZone
    "NameHeader": "Nome",
    "NomenclaturaHeader": "Nomenclatura",
    "TypeHeader": "Tipo",
    "MailHeader": "Correo electrónico",
    "OrgansHeader": "Órganos",
    "ManageLabel": "Xestionar",
    "NoResults": "Non se atoparon resultados",
    "PageNumberTxt": "Páxina",
    "FromTotalPageTxt": "de",
    "CertificateLabel": "Certificado",


  "Users": "Usuarios",
    "Organs": "Órganos",
    "properties": "prodpiedades",
    "List": "Listado",
    "Templates": "Plantillas",
    
    // prodPIEDADES ÓRGANO
    "DepartmentName": "Nome do órgano",
    "DepartmentNamePlaceholder": "Selecciona un órgano",
    "OrganType": "Tipo de órgano",
    "GeneralPlaceholder": "Seleccione un valor",
    "Ministry": "Division",
    "Nomenclature": "Nomenclatura",
    "Secretaria": "Secretaría",
    "Intersectorial": "Intersectorial",
    "Subject": "Materia",
    "BusinessArea": "Área sectorial",
    "Abbreviation": "Abreviatura",
    "Legislature": "Lexislatura",
    "CreationDate": "Data de constitución",
    "ExpirationDate": "Data de extinción",
    "DaysToApprodve": "Días para aprodbar a Minutes",
    "SIA": "SIA",
    "DIR3": "DIR3",
    "Description": "Descrición",
    "Observations": "Observacións",
    "ActiveStatus": "Estado",
    "ActiveYes": "Activo",
    "ActiveNo": "Inactivo",
    "IntersectorialYes": "Si",
    "IntersectorialNo": "Non",
    "SelectOrgan":"Selecciona un término existente",
    "CreateNewOrgan":"Crea un nuevo término",
    "DepartmentNameExist": "Xa existe outro órgano con este nome.",
    "CodigoDepartment": "Código órgano",
    "FechaInscripcion": "Data de inscrición",
    "StatusDepartment": "Situación",
    "DepartmentAdscripcion": "Órgano de adscripción",
    "Inscrito": "Inscrito",
    "YesLabel": "Sí",
    "NoLabel": "No",
    // prodPIEDADES USUARIO
    "Name": "Nome",
    "SurName": "Apelidos",
    "DisplayName": "Nome para mostrar",
    "Email": "Correo electrónico",
    "SecondaryMail": "Correo electrónico secundario",
    "PhoneNumber": "Teléfono móbil",
    "Job": "Cargo",
    "AutonomousCommunity": "Comunidade autónoma",

    "FieldRequired":"Este campo é obrigatorio.",
    "PhoneError":"Debe introducir un número de teléfono válido (9 díxitos consecutivos, sen espazos nin outros caracteres).",
    "MailError":"Debe introducir un email válido (formato: usuario@dominio.extensión).",

    // LISTADO USUARIOS / ÓRGANOS
    "Members": "Membros",
    "Role": "Roles",
    "Remove": "Eliminar",
    "AddNewUser": "Engadir usuario",
    "AddNewOrgan": "Engadir órgano",
    "SelectUserPlaceholder": "Selecciona un usuario",
    "SelectOrganPlaceholder": "Selecciona un órgano",
    "SelectRolePlaceholder": "Selecciona un rol",
    "SelectCCAAPlaceholder": "Selecciona una comunidad",
    "NeedLicense": "O usuario terá funcionalidade limitada ao non dispor de licenza",
    
    "ChangesDone": "Vanse realizar os seguintes cambios:",
    "AreYouSure": "Estás seguro de realizar estes cambios?",
    "NoChanges": "Non se realizaron cambios",
    "ECNTyValueChange":"(baleiro)",
    "SavingLoading": "Actualizando a información",
    "RemovedListItem": "Eliminado",
    "ErrorListOrgan": "Hai usuarios duplicados, revisa os cambios antes de gardar.",
    "ErrorListUser": "Hai órganos duplicados, revisa os cambios antes de gardar.",
    "UserDuplicated": "Xa hai unha entrada para este usuario no órgano.",
    "OrganDuplicated": "Xa hai unha entrada para este órgano no usuario.",
    "CheckPermissionsTooltip": "Comprodbe se os permisos do usuario se aplicaron correctamente",
    "UserLabel": "Usuario",
    "OrganLabel": "Órgano",
    "RoleLabel": "Rol",
    "CheckPermissionsLabel": "Comprodbación de permisos",
    "UserHasPermissionsTxt": "O usuario ten permisos no rol indicado",
    "UserNotPermissionsTxt": "O usuario aínda non dispón dos permisos no rol indicado",
    "Accept": "Aceptar",
    "PermissionsTimeNote": "Estes cambios poden tardar varios minutos en facerse efectivos.",
    "Warning": "Alert",
    "WarningMessage": "Os cambios realizados poden tardar uns minutos en reflectirse.",
    "WarningNameChange": "* O cambio de nome pode tardar uns minutos en aplicarse",
    "FechaCreacion": "Data creación",
    "DesdeFilter": "Desde",
    "HastaFilter": "Ata",
    "DocumentsTooltip": "Documents",

    "ErrorMsg": "Ocorreu un erro, inténtao máis tarde.",
    "Save": "Gardar",
    "Discard": "Descartar",
    "DuplicatedCode": "Xa existe outro órgano con este código.",

    "UploadDocument": "Subir Document",
    "FileRequired": "Debe subir un ficheiro.",
    "TipoDepartmentRequired": "O tipo de órgano é obrigatorio.",
    "TipoDocumentRequired": "O tipo de Document é obrigatorio.",
    "DepartmentRequired": "O órgano é obrigatorio.",
    "SelectFolderRequired": "Debe seleccionar un cartafol ou marcar 'Novo cartafol' para crear un novo.",
    "NewFolderRequired": "Debe indicar o nome do novo cartafol.",
    "FolderDuplicated": "Xa existe un cartafol con este nome.",
    "FileLabel": "Ficheiro",
    "DocumentTypeLabel": "Tipo de Document",
    "DocumentTypePlaceHolder": "Selecciona un tipo de Document",
    "FechaMeetingLabel": "Data da Meeting",
    "CarpetaReunionLabel": "Cartafol da reunión",
    "SelectFolderPlaceholder": "Selecciona o cartafol",
    "CreateNewFolder": "Crear novo cartafol?",
    "NewFolderName": "Nome do novo cartafol",
    "SavedOk": "Gardouse correctamente.",
    "SavingLoad": "Gardando...",
    "Close": "Pechar",
    "Cancel": "Cancelar"
  };
});