define([], function () {
  return {
    'NumberOfResults': 'Nombre de resultats',
    'GetPendingTasksFromThisSite': 'Obtenir aquest lloc',
    "Title": "Títol",
    'MoreLink': 'Veure tot',
    'MoreLinkLabel': 'Enllaç "Veure tot"',
    'LoadingThePendingTasks': 'Carregant les tasques pendents',
    'NoPendingTasksToShow': 'No hi ha tasques pendents per mostrar.',
    'MeetingAttendance': 'Assistència a la convocatòria',
    'AttendanceType': 'Tipus d\'assistència',
    'DelegateTheMeeting': 'Delegar la convocatòria',
    'MinutesApprodval': 'Aprodvació dMinutes',
    'MinutesModification': 'Modificació dMinutes',
    'CertificationApprodval': 'Aprodvació de certificació',
    'Attendance': 'Assistència',
    'Vote': 'Vot',
    'SelectAnOption': 'Seleccioneu una opció',
    'SelectAPerson': 'Seleccioneu una persona',
    'AdditionalComments': 'Comentaris addicionals',
    'WriteAComment': 'Escriviu un comentari',
    'RuleOut': 'Descartar',
    'Send': 'Enviar',
    'Sending': 'Enviant',
    'Accept': 'Acceptar',
    'Refuse': 'Rebutjar',
    'Delegate': 'Delegar',
    'Online': 'Online',
    'InPerson': 'InPerson',
    'ModifyMinutes': 'Modificar Minutes',
    'DropdownErrorMessage': 'Heu de seleccionar una opció.',
    'PeoplePickerErrorMessage': 'Heu de seleccionar una persona.',
    'PeoplePickerDelegationErrorMessage': 'No es pot delegar en un mateix.',
    'CommentsErrorMessage': 'El comentari no pot contenir més de 255 caràcters.',
    'BackendErrorMessage': 'S\'ha prodduït un error, torneu-ho a prodvar més tard.',
    'prefixMeetingAttendanceRequest': 'Sol·licitud dassistència',
    'prefixDelegatedMeetingAttendanceRequest': 'Sol·licitud de delegació',
    'prefixMinutesApprodvalRequest': 'Sol·licitud daprodvació dMinutes',
    'prefixMinutesModificationRequest': 'Sol·licitud de modificació dMinutes',
    'prefixCertificationRequest': 'Sol·licitud de certificació',
    'DelegateAssistanceTo': 'ha sol·licitat delegar l\'assistència a',
    'DelegateAssistanceAndVoteTo': 'ha sol·licitat delegar l\'assistència i el vot a',
    'DelegateVoteTo': 'i el vot a',
    'RequestToModifyTheMinutes': 'ha sol·licitat modificar l\'Minutes',
    'Reason': 'pel següent motiu',
    'ThereIsACertificationRequest': 'Hi ha una sol·licitud de certificació per al següent acord',
    'ViewMorePendingTasks': 'Veure més tasques pendents'
  }
});