define([], function () {
  return {
    'NumberOfResults': 'Number of results',
    'GetPendingTasksFromThisSite': 'Get from this site',
    "Title": "Title",
    'MoreLink': 'See all',
    'MoreLinkLabel': '"See all" link',
    'LoadingThePendingTasks': 'Loading the pending tasks',
    'NoPendingTasksToShow': 'There are no pending tasks to show.',
    'MeetingAttendance': 'Meeting at the attendance',
    'AttendanceType': 'Attendance type',
    'DelegateTheMeeting': 'Delegate the meeting',
    'MinutesApprodval': 'Minutes approdval',
    'MinutesModification': 'Minutes modification',
    'CertificationApprodval': 'Certification approdval',
    'Attendance': 'Attendance',
    'Vote': 'Vote',
    'SelectAnOption': 'Select an option',
    'SelectAPerson': 'Select a person',
    'AdditionalComments': 'Additional comments',
    'WriteAComment': 'Write a comment',
    'RuleOut': 'Rule out',
    'Send': 'Send',
    'Sending': 'Sending',
    'Accept': 'Accept',
    'Refuse': 'Refuse',
    'Delegate': 'Delegate',
    'Online': 'Online',
    'InPerson': 'InPerson',
    'ModifyMinutes': 'Modify minutes',
    'DropdownErrorMessage': 'You must select an option.',
    'PeoplePickerErrorMessage': 'You must select a person.',
    'PeoplePickerDelegationErrorMessage': 'You cannot delegate to yourself.',
    'CommentsErrorMessage': 'The comment cannot contain more than 255 characters.',
    'BackendErrorMessage': 'An error occurred, please try again later.',
    'prefixMeetingAttendanceRequest': 'Assistance request',
    'prefixDelegatedMeetingAttendanceRequest': 'Delegation request',
    'prefixMinutesApprodvalRequest': 'Minutes approdval request',
    'prefixMinutesModificationRequest': 'Minutes modification request',
    'prefixCertificationRequest': 'Certification request',
    'DelegateAssistanceTo': 'has requested to delegate attendance to',
    'DelegateAssistanceAndVoteTo': 'has requested to delegate the attendance and the vote to',
    'DelegateVoteTo': 'and the vote to',
    'RequestToModifyTheMinutes': 'has requested to modify the minutes',
    'Reason': 'for the following reason',
    'ThereIsACertificationRequest': 'There is a certification request for the following agreement',
    'ViewMorePendingTasks': 'View more pending tasks'
  }
});