define([], function () {
  return {
    'NumberOfResults': 'Número de resultados',
    'GetPendingTasksFromThisSite': 'Obtener de este sitio',
    "Title": "Título",
    'MoreLink': 'Ver todo',
    'MoreLinkLabel': 'Vínculo "Ver todo"',
    'LoadingThePendingTasks': 'Cargando las tareas pendientes',
    'NoPendingTasksToShow': 'No hay tareas pendientes para mostrar.',
    'MeetingAttendance': 'Attendance a la Meeting',
    'AttendanceType': 'Tipo de Attendance',
    'DelegateTheMeeting': 'Delegar la Meeting',
    'MinutesApprodval': 'Aprodbación de Minutes',
    'MinutesModification': 'Modificación de Minutes',
    'CertificationApprodval': 'Aprodbación de certificación',
    'Attendance': 'Attendance',
    'Vote': 'Voto',
    'SelectAnOption': 'Seleccione una opción',
    'SelectAPerson': 'Seleccione una persona',
    'AdditionalComments': 'Comentarios adicionales',
    'WriteAComment': 'Escriba un comentario',
    'RuleOut': 'Descartar',
    'Send': 'Enviar',
    'Sending': 'Enviando',
    'Accept': 'Aceptar',
    'Refuse': 'Rechazar',
    'Delegate': 'Delegar',
    'Online': 'Online',
    'InPerson': 'InPerson',
    'ModifyMinutes': 'Modificar Minutes',
    'DropdownErrorMessage': 'Debe seleccionar una opción.',
    'PeoplePickerErrorMessage': 'Debe seleccionar una persona.',
    'PeoplePickerDelegationErrorMessage': 'No se puede delegar en uno mismo.',
    'CommentsErrorMessage': 'El comentario no puede contener más de 255 caracteres.',
    'BackendErrorMessage': 'Se ha prodducido un error, vuelva a intentarlo más tarde.',
    'prefixMeetingAttendanceRequest': 'Request de Attendance',
    'prefixDelegatedMeetingAttendanceRequest': 'Request de delegación',
    'prefixMinutesApprodvalRequest': 'Request de aprodbación de Minutes',
    'prefixMinutesModificationRequest': 'Request de modificación de Minutes',
    'prefixCertificationRequest': 'Request de certificación',
    'DelegateAssistanceTo': 'ha solicitado delegar la Attendance a',
    'DelegateAssistanceAndVoteTo': 'ha solicitado delegar la Attendance y el voto a',
    'DelegateVoteTo': 'y el voto a',
    'RequestToModifyTheMinutes': 'ha solicitado modificar el Minutes',
    'Reason': 'por el siguiente motivo',
    'ThereIsACertificationRequest': 'Hay una Request de certificación para el siguiente acuerdo',
    'ViewMorePendingTasks': 'Ver más tareas pendientes'
  }
});