define([], function () {
  return {
    'NumberOfResults': 'Emaitza kopurua',
    'GetPendingTasksFromThisSite': 'Eskuratu gune honetatik',
    "Title": "Izenburua",
    'MoreLink': 'Ikusi dena',
    'MoreLinkLabel': '"Ikusi guztiak" esteka',
    'LoadingThePendingTasks': 'Zain dauden zereginak kargatzen',
    'NoPendingTasksToShow': 'Ez dago egiteke dagoen zereginik erakusteko.',
    'MeetingAttendance': 'Bileretarako asistentzia',
    'AttendanceType': 'Asistentzia mota',
    'DelegateTheMeeting': 'Bilera delegatzea',
    'MinutesApprodval': 'Akta onartzea',
    'MinutesModification': 'Akta aldaketa',
    'CertificationApprodval': 'Ziurtagiriaren onespena',
    'Attendance': 'Asistentzia',
    'Vote': 'Bozkatu',
    'SelectAnOption': 'Hautatu aukera bat',
    'SelectAPerson': 'Hautatu pertsona bat',
    'AdditionalComments': 'Iruzkin gehigarriak',
    'WriteAComment': 'Idatzi iruzkin bat',
    'RuleOut': 'Baztertu',
    'Send': 'Igorri',
    'Sending': 'Bidaltzen',
    'Accept': 'Onartu',
    'Refuse': 'Gainbehera',
    'Delegate': 'Delegatzera',
    'Online': 'Online',
    'InPerson': 'Pertsonalki',
    'ModifyMinutes': 'Aldatu aktak',
    'DropdownErrorMessage': 'Aukera bat hautatu behar duzu.',
    'PeoplePickerErrorMessage': 'Pertsona bat hautatu behar duzu.',
    'PeoplePickerDelegationErrorMessage': 'Ezin duzu zeure buruari delegatu.',
    'CommentsErrorMessage': 'Iruzkinak ezin du izan 255 karaktere baino gehiago.',
    'BackendErrorMessage': 'Errore bat gertatu da, mesedez berriro saiatu geroago.',
    'prefixMeetingAttendanceRequest': 'Joateko eskaera',
    'prefixDelegatedMeetingAttendanceRequest': 'Ordezkaritzaren eskaera',
    'prefixMinutesApprodvalRequest': 'Aktak onartzeko eskaera',
    'prefixMinutesModificationRequest': 'Aktak aldatzeko eskaera',
    'prefixCertificationRequest': 'Ziurtagiri eskaera',
    'DelegateAssistanceTo': 'laguntza emateko eskatu du',
    'DelegateAssistanceAndVoteTo': 'bertaratzea eta botoa emateko eskatu du',
    'DelegateVoteTo': 'eta botoa',
    'RequestToModifyTheMinutes': 'akta aldatzeko eskatu du',
    'Reason': 'honako arrazoi honengatik',
    'ThereIsACertificationRequest': 'Honako hitzarmen honen egiaztagiri-eskaera dago',
    'ViewMorePendingTasks': 'Ikusi zain dauden zeregin gehiago'
  }
});