define([], function () {
  return {
    'NumberOfResults': 'Número de resultados',
    'GetPendingTasksFromThisSite': 'Obtén desde este sitio',
    "Title": "Título",
    'MoreLink': 'Ver todo',
    'MoreLinkLabel': 'Ligazón "Ver todo"',
    'LoadingThePendingTasks': 'Cargando tarefas pendentes',
    'NoPendingTasksToShow': 'Non hai tarefas pendentes para mostrar.',
    'MeetingAttendance': 'Attendance á Meeting',
    'AttendanceType': 'Tipo de Attendance',
    'DelegateTheMeeting': 'Delegar a Meeting',
    'MinutesApprodval': 'Aprodbación de Minutes',
    'MinutesModification': 'Modificación de Minutes',
    'CertificationApprodval': 'Aprodbación de certificación',
    'Attendance': 'Attendance',
    'Vote': 'Voto',
    'SelectAnOption': 'Seleccione unha opción',
    'SelectAPerson': 'Selecciona unha persoa',
    'AdditionalComments': 'Comentarios adicionais',
    'WriteAComment': 'Escribe un comentario',
    'RuleOut': 'Descartar',
    'Send': 'Enviar',
    'Sending': 'Enviando',
    'Accept': 'Aceptar',
    'Refuse': 'Declinar',
    'Delegate': 'Delegado',
    'Online': 'Online',
    'InPerson': 'En persoa',
    'ModifyMinutes': 'Modificar Minutes',
    'DropdownErrorMessage': 'Debes seleccionar unha opción.',
    'PeoplePickerErrorMessage': 'Debes seleccionar unha persoa.',
    'PeoplePickerDelegationErrorMessage': 'Non podes delegar en ti mesmo.',
    'CommentsErrorMessage': 'O comentario non pode conter máis de 255 caracteres.',
    'BackendErrorMessage': 'prodduciuse un erro, téntao de novo máis tarde.',
    'prefixMeetingAttendanceRequest': 'Requeste de Attendance',
    'prefixDelegatedMeetingAttendanceRequest': 'Requeste de delegación',
    'prefixMinutesApprodvalRequest': 'Requeste de aprodbación de Minutes',
    'prefixMinutesModificationRequest': 'Requeste de modificación de Minutes',
    'prefixCertificationRequest': 'Requeste de certificación',
    'DelegateAssistanceTo': 'solicitou delegar Attendance en',
    'DelegateAssistanceAndVoteTo': 'solicitou delegar a Attendance e o en',
    'DelegateVoteTo': 'e o voto en',
    'RequestToModifyTheMinutes': 'solicitou modificar a Minutes',
    'Reason': 'polo seguinte motivo',
    'ThereIsACertificationRequest': 'Existe unha Requeste de certificación para o seguinte acordo',
    'ViewMorePendingTasks': 'Ver máis tarefas pendentes'
  }
});