define([], function () {
  return {
      "Users": "Usuaris",
      "Organs": "Òrgans",
      "properties": "prodpietats",
      "List": "Llistat",
      "Templates": "Plantilles",
      
      // prodPIETATS ÒRGAN
      "DepartmentName": "Nom de l'òrgan",
      "DepartmentNamePlaceholder": "Selecciona un òrgan",
      "OrganType": "Tipus d'òrgan",
      "GeneralPlaceholder": "Seleccioneu un valor",
      "Ministry": "Ministeri",
      "Nomenclature": "Nomenclatura",
      "Secretaria": "Secretaria",
      "Intersectorial": "Intersectorial",
      "BusinessArea": "Àrea sectorial",
      "Subject":"Matèria",
      "Abbreviation": "Abreviatura",
      "Legislature": "Period",
      "CreationDate": "Data de constitució",
      "ExpirationDate": "Data d'extinció",
      "DaysToApprodve": "Dies per aprodvar l'Minutes",
      "SIA": "SIA",
      "DIR3": "DIR3",
      "Description": "Descripció",
      "Observations": "Observacions",
      "ActiveStatus": "Estat",
      "ActiveYes": "Actiu",
      "ActiveNo": "Inactiu",
      "IntersectorialYes": "Sí",
      "IntersectorialNo": "No",
      "DepartmentNameExist": "Ja existeix un altre òrgan amb aquest nom.",
      "CodigoDepartment": "Codi òrgan",
      "FechaInscripcion": "Data d'inscripció",
      "StatusDepartment": "Situació",
      
      // prodPIETATS USUARI
      "Name": "Nom",
      "SurName": "Cognoms",
      "DisplayName": "Nom per mostrar",
      "Email": "Correu electrònic",
      "SecondaryMail": "Correu electrònic secundari",
      "PhoneNumber": "Telèfon mòbil",
      "Job": "Càrrec",
      "AutonomousCommunity": "Comunitat autònoma",
      "FieldRequired":"Aquest camp és obligatori.",
      "PhoneError":"Has d’introduir un número de telèfon vàlid (9 dígits consecutius, sense espais ni altres caràcters).",
      "MailError":"Has d’introduir un correu electrònic vàlid (format: usuari@domini.extensió).",
      "CompanyNameLabel": "Ministeri / Govern autonòmic",
      "DepartmentLabel": "Unitat / Conselleria",
      "EmployeeTypeLabel": "Tipus d’empleat",
      "BusinessPhoneLabel": "Telèfon de l’emtestsa",
      
      // LLISTAT USUARIS / ÒRGANS
      "Members": "Membres",
      "Role": "Rols",
      "Remove": "Eliminar",
      "AddNewUser": "Afegir usuari",
      "AddNewOrgan": "Afegir òrgan",
      "SelectUserPlaceholder": "Selecciona un usuari",
      "SelectOrganPlaceholder": "Selecciona un òrgan",
      "SelectRolePlaceholder": "Selecciona un rol",
      "SelectCCAAPlaceholder": "Selecciona una comunidad",
      "NeedLicense": "L'usuari tindrà funcionalitat limitada si no disposa de llicència",
      "SavingLoading": "Actualitzant la informació",

      "ChangesDone": "Es faran els següents canvis:",
      "AreYouSure": "Estàs segur de fer aquests canvis?",
      "NoChanges": "No s'han fet canvis",
      "ECNTyValueChange":"(buit)",
      "RemovedListItem": "Eliminat",
      "ErrorListOrgan": "Hi ha usuaris duplicats, revisa els canvis abans de desar.",
      "ErrorListUser": "Hi ha òrgans duplicats, revisa els canvis abans de desar.",
      "UserDuplicated": "Ja hi ha una entrada per a aquest usuari en l'òrgan.",
      "OrganDuplicated": "Ja hi ha una entrada per a aquest òrgan en l'usuari.",
      "CheckPermissionsTooltip": "Comprodva si els permisos de l'usuari s'han aplicat correctament",
      "UserLabel": "Usuari",
      "OrganLabel": "Òrgan",
      "RoleLabel": "Rol",
      "CheckPermissionsLabel": "Comprodvació de permisos",
      "UserHasPermissionsTxt": "L'usuari té permisos en el rol indicat",
      "UserNotPermissionsTxt": "L'usuari encara no disposa dels permisos en el rol indicat",
      "Accept": "Acceptar",
      "PermissionsTimeNote": "Aquests canvis poden trigar diversos minuts a fer-se efectius.",
      "Warning": "Avís",
      "WarningMessage": "Els canvis realitzats poden trigar uns minuts a reflectir-se.",
      
      "ErrorMsg": "S’ha prodduït un error, intenta-ho més tard.",
      "Save": "Desar",
      "Discard": "Descartar",

      //LICENSES
      "LicenseTitle": "Llicenciament",
      "LicensesStatus": "Estat de les llicències",
      "AvailablesLabel": "disponibles de",
      "License": "Llicència",
      "NoLicense": "Sense llicència",
      "DeleteLicense": "S'eliminarà la llicència per a l'usuari ",
      "AssingLicense": "S'assignarà la llicència ",
      "ForUser": " per a l'usuari ",
      "LicensesNotAvailable": "No s'ha pogut obtenir informació sobre les llicències"
  }
})