define([], function () {
    return {
        "Users": "Erabiltzaileak",
        "Organs": "Departmentak",
        "properties": "prodpietateak",
        "List": "Zerrenda",
        "Templates": "Txantiloiak",
        
        // DepartmentAREN prodPIETATEAK
        "DepartmentName": "Departmentaren izena",
        "DepartmentNamePlaceholder": "Hautatu Department bat",
        "OrganType": "Department mota",
        "GeneralPlaceholder": "Hautatu balio bat",
        "Ministry": "Divisiona",
        "Nomenclature": "Nomenklatura",
        "Secretaria": "Idazkaritza",
        "Intersectorial": "Sektore artekoa",
        "Subject": "Gaia",
        "BusinessArea": "Sektore arloa",
        "Abbreviation": "Laburdura",
        "Legislature": "Legegintzaldia",
        "CreationDate": "Sortze data",
        "ExpirationDate": "Amaiera data",
        "DaysToApprodve": "Aktak onartzeko egunak",
        "SIA": "SIA",
        "DIR3": "DIR3",
        "Description": "Deskribapena",
        "Observations": "Oharrak",
        "ActiveStatus": "Egoera",
        "ActiveYes": "Aktiboa",
        "ActiveNo": "Inaktiboa",
        "IntersectorialYes": "Bai",
        "IntersectorialNo": "Ez",
        "SelectOrgan":"Selecciona un término existente",
        "CreateNewOrgan":"Crea un nuevo término",
        "DepartmentNameExist": "Izen honekin beste Department bat dago jada.",
        "CodigoDepartment": "Department kodea",
        "FechaInscripcion": "Erregistro data",
        "StatusDepartment": "Egoera",
        
        // ERABILTZAILEAREN prodPIETATEAK
        "Name": "Izena",
        "SurName": "Abizenak",
        "DisplayName": "Erakutsi izena",
        "Email": "Posta elektronikoa",
        "SecondaryMail": "Bigarren posta elektronikoa",
        "PhoneNumber": "Telefono mugikorra",
        "Job": "Kargua",
        "AutonomousCommunity": "Autonomia erkidegoa",
        "FieldRequired":"Eremu hau derrigorrezkoa da.",
        "PhoneError":"Telefono zenbaki baliodun bat sartu behar duzu (9 zenbaki jarraian, espaziorik edo beste karaktererik gabe).",
        "MailError":"Baliozko email bat sartu behar duzu (formatua: erabiltzailea@domeinua.hedapena).",
        "CompanyNameLabel": "Divisiona / Autonomia Gobernua",
        "DepartmentLabel": "Unitatea / Sailburutza",
        "EmployeeTypeLabel": "Langile mota",
        "BusinessPhoneLabel": "Entestsako telefonoa",
        
        // ERABILTZAILEAK / DepartmentAK ZERRENDA
        "Members": "Kideak",
        "Role": "Rolak",
        "Remove": "Ezabatu",
        "AddNewUser": "Erabiltzailea gehitu",
        "AddNewOrgan": "Departmenta gehitu",
        "SelectUserPlaceholder": "Hautatu erabiltzaile bat",
        "SelectOrganPlaceholder": "Hautatu Department bat",
        "SelectRolePlaceholder": "Hautatu rol bat",
        "SelectCCAAPlaceholder": "Selecciona una comunidad", 
        
        "ChangesDone": "Hurrengo aldaketak egingo dira:",
        "AreYouSure": "Ziur zaude aldaketa hauek egin nahi dituzula?",
        "NoChanges": "Ez da aldaketarik egin",
        "ECNTyValueChange":"(hutsik)",
        "SavingLoading": "Informazioa eguneratzen",
        "RemovedListItem": "Ezabatua",
        "NeedLicense": "Erabiltzaileak funtzionalitate mugatua izango du lizentziarik gabe",
        "ErrorListOrgan": "Erabiltzaile bikoiztuak daude, berrikus aldaketak gorde aurretik.",
        "ErrorListUser": "Department bikoiztuak daude, berrikus aldaketak gorde aurretik.",
        "UserDuplicated": "Erabiltzaile honetarako sarrera bat dago Departmentan.",
        "OrganDuplicated": "Department honetarako sarrera bat dago erabiltzailean.",
        "CheckPermissionsTooltip": "Erabiltzailearen baimenak behar bezala aplikatu diren egiaztatu",
        "UserLabel": "Erabiltzailea",
        "OrganLabel": "Departmenta",
        "RoleLabel": "Rola",
        "CheckPermissionsLabel": "Baimenen egiaztapena",
        "UserHasPermissionsTxt": "Erabiltzaileak adierazitako rolaren baimenak ditu",
        "UserNotPermissionsTxt": "Erabiltzaileak oraindik ez ditu adierazitako rolaren baimenak",
        "Accept": "Onartu",
        "PermissionsTimeNote": "Aldaketa hauek hainbat minutu behar izan ditzakete eraginkorrak izateko.",
        "Warning": "Abisua",
        "WarningMessage": "Egindako aldaketak minutu batzuk behar izan ditzake islatzeko.",
        "Warning": "Abisua",
        "WarningMessage": "Egindako aldaketak minutu batzuk behar izan ditzake islatzeko.",
       
        "ErrorMsg": "Errore bat gertatu da, saiatu geroago.",
        "Save": "Gorde",
        "Discard": "Baztertu",

        //LICENSES
        "LicenseTitle": "Lizentziamendua",
        "LicensesStatus": "Lizentzien egoera",
        "AvailablesLabel": "eskuragarri",
        "License": "Lizentzia",
        "NoLicense": "Lizentziarik gabe",
        "DeleteLicense": "Erabiltzailearentzako lizentzia ezabatuko da ",
        "AssingLicense": "Lizentzia esleituko da ",
        "ForUser": " erabiltzailearentzat ",
        "LicensesNotAvailable": "Ezin izan da lizentzien inguruko informaziorik lortu"
    }
})