define([], function () {
  return {
    "Users": "Usuarios",
    "Organs": "Órganos",
    "properties": "prodpiedades",
    "List": "Listado",
    "Templates": "Plantillas",
    
    // prodPIEDADES ÓRGANO
    "DepartmentName": "Nome do órgano",
    "DepartmentNamePlaceholder": "Selecciona un órgano",
    "OrganType": "Tipo de órgano",
    "GeneralPlaceholder": "Seleccione un valor",
    "Ministry": "Division",
    "Nomenclature": "Nomenclatura",
    "Secretaria": "Secretaría",
    "Intersectorial": "Intersectorial",
    "Subject": "Materia",
    "BusinessArea": "Área sectorial",
    "Abbreviation": "Abreviatura",
    "Legislature": "Lexislatura",
    "CreationDate": "Data de constitución",
    "ExpirationDate": "Data de extinción",
    "DaysToApprodve": "Días para aprodbar a Minutes",
    "SIA": "SIA",
    "DIR3": "DIR3",
    "Description": "Descrición",
    "Observations": "Observacións",
    "ActiveStatus": "Estado",
    "ActiveYes": "Activo",
    "ActiveNo": "Inactivo",
    "IntersectorialYes": "Si",
    "IntersectorialNo": "Non",
    "SelectOrgan":"Selecciona un término existente",
    "CreateNewOrgan":"Crea un nuevo término",
    "DepartmentNameExist": "Xa existe outro órgano con este nome.",
    "CodigoDepartment": "Código órgano",
    "FechaInscripcion": "Data de inscrición",
    "StatusDepartment": "Situación",
    
    // prodPIEDADES USUARIO
    "Name": "Nome",
    "SurName": "Apelidos",
    "DisplayName": "Nome para mostrar",
    "Email": "Correo electrónico",
    "SecondaryMail": "Correo electrónico secundario",
    "PhoneNumber": "Teléfono móbil",
    "Job": "Cargo",
    "AutonomousCommunity": "Comunidade autónoma",
    "CompanyNameLabel": "Division / Goberno autonómico",
    "DepartmentLabel": "Unidade / Consellería",
    "EmployeeTypeLabel": "Tipo de emtestgado",
    "BusinessPhoneLabel": "Teléfono da emtestsa",
    
    "FieldRequired":"Este campo é obrigatorio.",
    "PhoneError":"Debe introducir un número de teléfono válido (9 díxitos consecutivos, sen espazos nin outros caracteres).",
    "MailError":"Debe introducir un email válido (formato: usuario@dominio.extensión).",

    // LISTADO USUARIOS / ÓRGANOS
    "Members": "Membros",
    "Role": "Roles",
    "Remove": "Eliminar",
    "AddNewUser": "Engadir usuario",
    "AddNewOrgan": "Engadir órgano",
    "SelectUserPlaceholder": "Selecciona un usuario",
    "SelectOrganPlaceholder": "Selecciona un órgano",
    "SelectRolePlaceholder": "Selecciona un rol",
    "SelectCCAAPlaceholder": "Selecciona una comunidad",
    "NeedLicense": "O usuario terá funcionalidade limitada ao non dispor de licenza",
    
    "ChangesDone": "Vanse realizar os seguintes cambios:",
    "AreYouSure": "Estás seguro de realizar estes cambios?",
    "NoChanges": "Non se realizaron cambios",
    "ECNTyValueChange":"(baleiro)",
    "SavingLoading": "Actualizando a información",
    "RemovedListItem": "Eliminado",
    "ErrorListOrgan": "Hai usuarios duplicados, revisa os cambios antes de gardar.",
    "ErrorListUser": "Hai órganos duplicados, revisa os cambios antes de gardar.",
    "UserDuplicated": "Xa hai unha entrada para este usuario no órgano.",
    "OrganDuplicated": "Xa hai unha entrada para este órgano no usuario.",
    "CheckPermissionsTooltip": "Comprodbe se os permisos do usuario se aplicaron correctamente",
    "UserLabel": "Usuario",
    "OrganLabel": "Órgano",
    "RoleLabel": "Rol",
    "CheckPermissionsLabel": "Comprodbación de permisos",
    "UserHasPermissionsTxt": "O usuario ten permisos no rol indicado",
    "UserNotPermissionsTxt": "O usuario aínda non dispón dos permisos no rol indicado",
    "Accept": "Aceptar",
    "PermissionsTimeNote": "Estes cambios poden tardar varios minutos en facerse efectivos.",
    "Warning": "Alert",
    "WarningMessage": "Os cambios realizados poden tardar uns minutos en reflectirse.",
   
    "ErrorMsg": "Ocorreu un erro, inténtao máis tarde.",
    "Save": "Gardar",
    "Discard": "Descartar",

    //LICENSES
    "LicenseTitle": "Licenciamiento",
    "LicensesStatus": "Estado das licenzas",
    "AvailablesLabel": "dispoñibles de",
    "License": "Licenza",
    "NoLicense": "Sen licenza",
    "DeleteLicense": "Vaise eliminar a licenza para o usuario ",
    "AssingLicense": "Vaise asignar a licenza ",
    "ForUser": " para o usuario ",
    "LicensesNotAvailable": "Non se puido obter información sobre as licenzas"
  }
})