define([], function () {
    return {
        /* General strings */
        'MeetingPoints': 'Ordre del dia',
        'Assistants': 'Assistents',
        'Documents': 'Documents',
        'Agreements': 'Acords',
        'Minutes': 'Minutes',
        'No': 'No',
        'Yes': 'Sí',
        'RuleOut': 'Descartar',
        'Close': 'Tancar',
        'Cancel': 'Cancel',
        'Delete': 'Eliminar',
        'Edit': 'Editar',
        'Replace': 'Reemplaçar',
        'Reselect': 'Tornar a seleccionar',
        'Accept': 'Acceptar',
        'Save': 'Guardar',
        'Send': 'Enviar',
        'Upload': 'Pujar',
        'Publish': 'Publicar',
        'Create': 'Crear',
        'Request': 'Sol·licitar',
        'LookFor': 'Cerca',
        'Visualize': 'Visualitzar',
        'Archive': 'Arxivar',
        'AssociateDocument': 'Associar document',
        'Loading': 'Carregant',
        'Deleting': 'Eliminant',
        'Canceling': 'Cancel·lant',
        'Publishing': 'Publicant',
        'Sending': 'Enviant',
        'Requesting': 'Sol·licitant',
        'CommentRequired': 'Heu d\'escriure un comentari.',
        'MessageRequired': 'Heu d\'escriure un missatge.',
        'BackendErrorMessage': 'S\'ha prodduït un error, torneu-ho a prodvar més tard.',
        'SendUpdate': 'Enviar actualització',
        'SendingUpdate': 'Enviant actualització',
        'Attendance': 'Assistència',
        'Certification': 'Certificació',
        'Online': 'Online',
        'InPerson': 'InPerson',

        /* MeetingWebPart strings */
        'NoResultsFound': 'No s\'han trobat resultats.',
        'ShowMoreSubtitle': 'Veure més',
        'FailUploadFile': 'Error en carregar el fitxer.',
        'CancelUploadFile': 'Descartar fitxer',
        'ButtonUploadFile': 'Pujar fitxers',
        'MaximumFilesTitle': 'Nombre màxim de fitxers',
        'MaximumFilesMessage': 'Ho sentim, la quantitat màxima de fitxers que pots pujar alhora és {MaxNumber}. Vols pujar els {MaxNumber} primers fitxers o tornar-los a seleccionar?',
        'MaximumFileSizeTitle': 'Mida màxima del fitxer',
        'MaximumFileSizeMessage': 'Ho sentim, la mida màxima del fitxer per pujar és {FileSize}. La mida del fitxer "{FileName}" és {FileSize}.',
        'FileTypeTitle': 'Tipus d\'arxiu',
        'FileTypeMessage': 'Ho sentim, no es pot pujar el format del fitxer "{FileName}".',
        'CheckAgain': 'No tornar a mostrar',
        'CheckApplyAll': 'Aplicar a tot',
        'ButtonOk': 'OK',
        'ButtonKeep': 'Mantenir tots dos',
        'FileReplaceTitle': 'Reemplaçar el fitxer',
        'FileReplaceMessage': 'Voleu reemplaçar el fitxer "{FileName}" o conservar tots dos fitxers?',
        'UploadButtonLabel': 'Botó de pujar fitxers',

        /* Meeting strings */
        'ThereAreNoMeetingsToShow': 'No teniu convocatòries per mostrar.',
        'TheMeetingIsBeingArchived': 'S\'està arxivant la convocatòria seleccionada, els detalls estaran disponibles en uns instants.',
        'TheMeetingIsNotAvailable': 'La convocatòria sol·licitada no està disponible o ha estat arxivada.',

        /* MeetingList strings */
        'NextMeetings': 'prodperes',
        'CelebratedMeetings': 'Celebrades',
        'ArchivedMeetings': 'Arxivades',
        'VideoconferenceMeetingList': 'Unir-se',

        /* MeetingStatusBar strings */
        'Videoconference': 'Unir-se a la Videoconferència',
        'LinkAvailableSoon': 'L\'enllaç estarà disponible 30 minuts abans del començament de la reunió',
        'ReserveAgenda': 'Reservar agenda',
        'UrgentNotification': 'Avís urgent',
        'WriteAnUrgentNotification': 'Escriviu un missatge (màxim 160 caràcters)',
        'MaximumCharactersForUrgentNotification': 'El missatge no pot contenir més de 160 caràcters.',
        'DeleteMeeting': 'Eliminar convocatòria',
        'CancelMeeting': 'Cancel·lar convocatòria',
        'StartMeeting': 'Iniciar reunió',
        'StartMeetingprodcEscrito': 'Iniciar prodcediment',
        'StartMeetingRemDocumentacion': 'Acords i Assistents',
        'FinishMeeting': 'Finalitzar convocatòria',
        'PublishMeeting': 'Publicar convocatòria',
        'testBookMeeting': 'Reservar agenda',
        'ArchiveMeeting': 'Arxivar',
        'SendUpdatesToAllAttendees': 'Enviar actualitzacions a tots els assistents de la convocatòria',
        'ThereAreNoUpdatesToSend': 'No hi ha actualitzacions per enviar',
        'QuestionToDeleteTheMeeting': 'Estàs segur que vols eliminar aquesta convocatòria?',
        'QuestionToCancelTheMeeting': 'Estàs segur que vols cancel·lar aquesta convocatòria?',
        'QuestionToFinishTheMeeting': 'Estàs segur que vols finalitzar aquesta convocatòria?',
        'QuestionToPublishTheMeeting': 'Estàs segur que vols publicar aquesta convocatòria?',
        'QuestionTotestBookTheMeeting': "Estàs segur que vols reservar a l'agenda aquesta convocatòria?",
        'QuestionToStartTheMeeting': 'Estàs segur que vols iniciar aquesta convocatòria?',
        'QuestionToArchiveTheMeeting': 'Estàs segur que vols arxivar aquesta convocatòria?',
        'UpdateMeeting': 'Actualitzar convocatòria',
        'FirstPhraseToUpdateTheMeeting': 'A continuació, es mostren les modificacions pendents de la convocatòria',
        'SecondPhraseToUpdateTheMeeting': 'que s\'aplicaran en prémer el botó \'Actualitzar\'.',
        'BasicData': 'Dades bàsiques',
        'NewTitle': 'Títol',
        'NewLocation': 'Ubicació',
        'NewLocationInformation': 'Detall de la ubicació',
        'NewMeetingType': 'Tipus de reunió',
        'NewDescription': 'Descripció',
        'NewStartDate': 'Data d\'inici',
        'NewEndDate': 'Data de fi',
        'NewOnlineTool': 'Eina online',
        'NewOnlineToolUrl': 'Url de l\'eina online',
        'TheOrderOfTheDayHasBeenUpdated': 'S\'ha actualitzat l\'ordre del dia.',
        'AddedAssistants': 'Assistents afegits',
        'RemovedAssistants': 'Assistents eliminats',
        'EditTheMeetingDetails': 'Editar els detalls de la convocatòria',
        'SeeTheMeetingDetails': 'Veure els detalls de la convocatòria',

        /* MeetingVoting strings */
        'Vote': 'Votar',
        'ShowQRCode': 'Mostra codi QR',
        'ManagingResults': 'Gestionar resultats',
        'ViewResults': 'Visualitzar resultats',
        'LoadingVotes': 'Carregant les Votes',
        'VotingPanel': 'Panell de retestsentants',
        'StartVoting': 'Iniciar Votes',
        'NoVotesToDisplay': 'No hi ha punts decisoris per votar.',
        'VotingNotStarted': 'La votació encara no ha començat.',
        'Approdve': 'A favor',
        'Reject': 'En contra',
        'Pending': 'Abstenció',
        'Abstention': 'Pendent',
        'StartTheVotingPeriod': 'Iniciar el període de votació',
        'ListOfVoters': 'Llistat de votants',
        'DescriptionOfStartingTheVotingPeriod': 'Els següents usuaris podran votar en iniciar el període de votació',
        'DescriptionOfTheVotingPeriodStarted': 'Els següents usuaris podran votar',
        'ShowNoVotes': 'No hi ha votants',
        'Update': 'Actualitzar',
        'MeetingVotingClose': 'Tancar',
        'ErrorToCreateQRCode': "S'ha prodduït un error en crear el codi QR",
        'QRCode': 'Codi QR',
        'GeneratingTheQRCode': 'Generant el codi QR',
        'MeetingVotingMustSelectOption': 'Heu de seleccionar una opció.',
        'DeselectOption': 'Desseleccionar opció',
        'ConfirmVote': 'Confirmar vot',
        'ConfirmChosenOption': "Confirmeu l'opció escollida",
        'Back': 'Enrere',
        'SubmitVote': 'Enviar vot',
        'Members': 'Membres',
        'Conveners': 'Convocants',
        'Member': 'Membre',
        'Convener': 'Convocant',
        'NoPermissionToVote': 'No tens permís per votar en aquesta convocatòria.',
        'VoteAlreadyRegisteredByTheUser': "Ja heu registrat el vostre vot. L'opció seleccionada és",
        'ContactToChangeYourVote': "Si voleu modificar el vostre vot, contacteu amb la Secretaria de l'Òrgan.",
        'CloseVoting': 'Votació finalitzada',
        'CloseVotingVote': 'Votació finalitzada, ha votat: ',
        'CloseVotingNoVote': 'Votació finalitzada, no ha votat',
        'StartingTheVotingPeriod': 'Iniciant el període de votació',
        'SavingChanges': 'Desant els canvis realitzats, això pot trigar uns instants...',
        'SendingVote': 'Enviant el seu vot',
        'VotingHasEndedAndYouDidNotVote': 'El període de votació ha finalitzat.',
        'testsidenciaLabel': 'testsidència',
        'VotingStatusTitle': 'Resultat de la votació',
        'FinishedStatus': 'Finalitzat',
        'FinishVotationChooseResult': 'Per finalitzar la votació d\'aquest punt, si us plau seleccioneu el resultat:',

        /* MeetingPoints strings */
        'DeleteTheOrderOfTheDay': 'Esborra l\'ordre del dia',
        'DoYouWantToDeleteTheOrderOfTheDay': 'Voleu eliminar l\'ordre del dia ',
        'Title': 'Títol',
        'Description': 'Descripció',
        'DownloadTheOrderOfTheDay': 'Descarrega l\'ordre del dia',
        'AddPointOfTheOrderOfTheDay': 'Afegeix el punt de l\'ordre del dia',
        'DeleteAssociatedDoc': 'Voleu desasociar el document ',
        'ErrorTitleRequired': 'El camp Títol és obligatori',
        'ErrorDurationRequired': 'El camp Durada és obligatori',
        'ErrorDuration': 'Només es permeten valors superiors a 0',
        'DeleteAssociation': 'Eliminar associació',
        'FromTheOrderOfTheDay': 'de l\'ordre del dia',
        'ThereAreNoPointsToShow': 'No hi ha punts de l\'ordre del dia per mostrar.',
        'LoadingPoint': 'Carregant els punts de lordre del dia',
        'ReorderItems': 'Reordenar',
        'AddSubPoint': 'Afegir subpunt',
        'ReorderInfoMessage': "Reordeneu els punts d'ordre del dia",
        'UpSameLevel': 'Pujar mateix nivell',
        'DownSameLevel': 'Baixar mateix nivell',
        'prodmoteDifferentLevel': 'Ascendir de nivell',
        'DecreaseDifferentLevel': 'Baixar de nivell',
        "CancelReorderModeMessage": "Els canvis realitzats no s'aplicaran. Estàs segur de realitzar aquesta acció?",
        "DiscardChangesTitle": "Desfer canvis realitzats",
        "CancelOrdenation": "Desfer ordenació",
        "SaveOrdenation": "Guardar ordenació",
        "SaveChangesMade": "Guardar canvis realitzats",
        "SaveChangesMessage": "Vols guardar els canvis realitzats en l'ordenació de l'ordre del dia?",
        "TooltipMessageFirstElement": "No disponible sobre el primer element d'un nivell",
        "TooltipMessageLastElement": "No disponible sobre l'últim element d'un nivell",
        "TooltipMessageTopElementIsDecisive": "No disponible quan el seu element superior és decisiu",
        "TooltipMessageWithoutTopElements": "No disponible quan no existeix un nivell superior",
        "TooltipMessageNoSubordersInDecisiveElements": "No disponible sobre ordres decisòries",
        "TooltipMessageNoDeleteElementoWithSuborders": "No disponible sobre ordres amb subordres",
        "TooltipMessageMaxLevel": "S'ha assolit el límit de subnivells",

        /* MeetingDocs strings */
        'Home': 'Inici',
        'GeneralOfTheMeeting': 'General de la convocatòria',
        'AddDocument': 'Afegir document',
        'RefreshDocuments': 'Actualitzar documents',
        'NoLabel': 'Cap',
        'SignedLabel': 'Aquest document està signat, per tant no s’hi pot aplicar cap etiqueta',
        'NoAvailableToLabel': 'No aplicable',
        'ExternalLabelTooltip': 'Aquest document no es pot convertir a PDF en publicar-lo, per tant es recomana eliminar-lo i pujar-lo sense etiquetatge extern',
        'ExternalLabel': 'Etiqueta externa',
        'LabelOnprocess': 'S’està aplicant l’etiqueta en aquests moments',
        'LabelApplied': 'Aquest document té una etiqueta aplicada',
        'NoLabelApplied': 'El document no està etiquetat',
        'UpdatingDocumentLabel': 'Aplicar etiqueta al document',
        'DocumentLabel': 'Document',
        'TagLabel': 'Etiqueta',
        'AreYouSure': 'Estàs segur de voler aplicar aquest canvi?',
        'DocHasOtherError': 'El document no és compatible amb les etiquetes',


        /* MeetingAssistants strings */
        'Pending': 'Pendent',
        'Accepted': 'Acceptat',
        'Refused': 'Rebutjat',
        'Delegated': 'Delegat',
        'RefusedAndDelegated': 'Rebutjat i Delegat',
        'NotSummoned': 'No convocat',
        'AttendeesList': 'Llista d\'assistents',
        'AddAssistant': 'Afegir assistent',
        'AddAUser': 'Afegeix un usuari',
        'ThereAreNoAssistanceToShow': 'No hi ha assistents per mostrar.',
        'UserAlreadyAdded': 'L\'usuari que heu introduït ja està agregat',
        'UserRequired': 'S\'ha de seleccionar un usuari per afegir-lo',
        'DownloadTheAttendanceReport': 'Descarregueu l\'informe d\'assistència',
        'CheckTheUsersWhoAttendedTheMeeting': 'Marqueu els usuaris que hagin assistit a la reunió',
        'UserPendingApprodval': 'Pendent daprodvació',
        'ReportAttendance': 'Informar assistència',
        'CancelAttendance': 'Cancel·lar assistència',
        'CancelAttendanceText': 'Es cancel·larà l\'assistència a la reunió del següent usuari:',
        'LoadingAttendees': 'Carregant els assistents',
        'AttendanceDelegation': 'Delegació dassistència',
        'VoteDelegation': 'Delegació de vot',
        'FailedToReportAssistance': "No s'ha pogut informar l'assistència, torneu-ho a prodvar més tard",

        /* MeetingAgreements strings */
        'LoadingTheAgreements': 'Carregant els acords',
        'NoAgreementsAvailable': 'No hi ha acords per mostrar.',
        'SelectAll': 'Seleccioneu tots',
        'DownloadCertification': 'Descarregar certificació',
        'WriteATitle': 'Escriviu un títol',
        'WriteADescription': 'Escriviu una descripció',
        'RequestCertificate': 'Sol·licitar certificat',
        'CertificateRequestQuestion': 'Voleu sol·licitar el certificat d\'acord',
        'AssociateSignedCertificate': 'Associar certificat signat',
        'CertificateAlreadyRequested': 'Ja heu sol·licitat el certificat d\'aquest acord',

        /* MeetingMinutes strings */
        'LoadingTheMinuteSections': 'Carregant l\'Minutes',
        'NoMinuteSectionsAvailable': 'No hi ha una Minutes per mostrar.',
        'WriteANote': 'Escriviu una nota',
        'WriteAComment': 'Escriviu un comentari',
        'ViewMinutes': 'Visualitzar Minutes',
        'RequestModificationOfTheMinutes': 'Sol·licitar modificació de l\'Minutes',
        'DownloadMinutes': 'Descarregar plantilla Minutes',
        'AssociateMinutes': 'Associar Minutes',
        'StatusApprodvalMinutes': 'Estat aprodvació Minutes',
        'ApprodvalsAccepted': 'Aprodvacions',
        'ApprodvalsPendingModification': 'Sol·licituds de modificació',
        'ApprodvalsRejected': 'Rebuigs',
        'ApprodvalsPendings': 'Pendents',
        'ValidationPeriod': 'El període de validació finalitza el ',
        'RequestApprodveMinutes': 'Sol·licitar aprodvació Minutes',
        'RequestApprodveMinutesText': 'Esteu segur que voleu iniciar el prodcés d\'aprodvació de l\'Minutes?',
        'ApprodveMinutes': 'Aprodvació d\'Minutes',
        'AttendanceDialogTitle': 'Aprodvadors de l\'Minutes',
        'AttendanceDialogDescription': 'L\'Minutes que cal associar serà aprodvada pels assistents a la convocatòria.',
        'AttendanceDialogClarification': 'Podeu informar l\'assistència a la convocatòria des de la pestanya "Assistents".',
        'AttendanceDialogNoItems': 'No s\'ha informat de l\'assistència de cap usuari.',
        'MoreDetailMinutes': 'Més detall...',
        'DetailMinutesTitle': 'Detall de l\'estat d\'aprodvació',

        /* MeetingNew strings */
        'CreateConvo': 'Crear convocatòria',
        'OnlineToolLabel': 'Opcions Eina online',
        'PlaceholderDescription': 'Si us plau, configureu el web part',
        'PlaceholderIconText': 'Configureu el web part',
        'PlaceholderButtonLabel': 'Configura',
        'AtendanceTypeLabel': 'Tipus d\'assistència',
        'TermGroupLabel': 'Grup de termes (Id)',
        'TitlePlaceholder': 'Afegeix un títol',
        'StartDatePlaceholder': 'Inici',
        'EndDatePlaceholder': 'Final',
        'LocationPlaceholder': 'Afegeix una ubicació',
        'OnlineLabel': 'Convocatòria en línia',
        'LocationDescriptionPlaceholder': 'Afegeix informació addicional a la ubicació',
        'OnlineToolPlaceholder': 'Seleccioneu una eina',
        'AttendanceTypePlaceholder': 'Seleccioneu tipus d\'assistència',
        'UrlPlaceholder': 'Enllaç convocatòria Reúnete',
        'PeoplePlaceholder': 'members (con voto)',
        'DescriptionPlaceholder': 'Escriviu els detalls de la convocatòria',
        'NewConvo': 'Nova convocatòria',
        'RequiredField': 'Camp obligatori.',
        'MinimumCharactersForTitle': 'El títol ha de tenir un mínim de 2 caràcters.',
        'MaximumCharactersForTitle': 'El títol ha de tenir un màxim de 255 caràcters.',
        'MaximumCharactersForDescription': 'La descripció ha de tenir un màxim de 1500 caràcters.',
        'StartDateLessThanTheCurrentDate': 'La data inicial no pot ser menor que la data actual.',
        'EndDateLessThanStartDate': 'La data final no pot ser menor que la data inicial.',
        'MaximumCharactersForLocation': 'La ubicació ha de tenir un màxim de 255 caràcters.',
        'MaximumCharactersForLocationDetails': 'Els detalls de la ubicació han de tenir un màxim de 255 caràcters.',
        'RequiredUrl': 'És obligatori introduir un enllaç.',
        'RequiredValidUrl': 'Introduïu un enllaç vàlid.',
        'MaximumCharactersForUrl': 'L\'enllaç ha de tenir un màxim de 255 caràcters.',
        'RequiredAttendanceTypeId': 'És obligatori triar el tipus dassistència.',
        'RequiredAttendees': 'És obligatori indicar almenys una persona.',
        'GuestPeoplePlaceholder': 'Asistentes (sin voto)',
        'Saving': 'Guardant',

        /* MeetingForm strings */
        'EditMeeting': 'Editar convocatòria',
        'NewMeeting': 'Nova convocatòria',
        'MeetingDetails': 'Detalls de la convocatòria',

        /* NewDocForm strings */
        'Document': 'Document',
        'SelectADocument': 'Seleccioneu un document',
        'SelectingADocumentIsRequired': 'Heu de seleccionar un document per associar-lo.',
        'AssociateTo': 'Associar a'
    }
});