define([], function () {
    return {
        /* General strings */
        'MeetingPoints': 'Order of the day',
        'Assistants': 'Assistants',
        'Documents': 'Documents',
        'Agreements': 'Agreements',
        'Minutes': 'Minutes',
        'No': 'No',
        'Yes': 'Yes',
        'RuleOut': 'Rule out',
        'Close': 'Close',
        'Cancel': 'Cancel',
        'Delete': 'Delete',
        'Edit': 'Edit',
        'Replace': 'Replace',
        'Reselect': 'Reselect',
        'Accept': 'Accept',
        'Save': 'Save',
        'Send': 'Send',
        'Upload': 'Upload',
        'Publish': 'Publish',
        'Create': 'Create',
        'Request': 'Request',
        'LookFor': 'Look for',
        'Visualize': 'Visualize',
        'Archive': 'Archive',
        'AssociateDocument': 'Associate document',
        'Loading': 'Loading',
        'Deleting': 'Deleting',
        'Canceling': 'Canceling',
        'Publishing': 'Publishing',
        'Sending': 'Sending',
        'Requesting': 'Requesting',
        'CommentRequired': 'You must write a comment.',
        'MessageRequired': 'You must write a message.',
        'BackendErrorMessage': 'An error has occurred, please try again later.',
        'SendUpdate': 'Send update',
        'SendingUpdate': 'Sending update',
        'Attendance': 'Attendance',
        'Certification': 'Certification',
        'Online': 'Online',
        'InPerson': 'InPerson',

        /* MeetingWebPart strings */
        'NoResultsFound': 'No results found.',
        'ShowMoreSubtitle': 'See more',
        'FailUploadFile': 'Error loading file.',
        'CancelUploadFile': 'Discard file',
        'ButtonUploadFile': 'Upload files',
        'MaximumFilesTitle': 'Maximum number of files',
        'MaximumFilesMessage': 'Sorry, the maximum number of files you can upload at once is {MaxNumber}. Do you want to upload the first {MaxNumber} files or reselect?',
        'MaximumFileSizeTitle': 'Maximum file size',
        'MaximumFileSizeMessage': 'Sorry, the maximum file size to upload is {FileSize}. The size of file "{FileName}" is {FileSize}.',
        'FileTypeTitle': 'File type',
        'FileTypeMessage': 'Sorry, the format of the file "{FileName}" cannot be uploaded.',
        'CheckAgain': 'Don\'t show again',
        'CheckApplyAll': 'Aplicar a todo',
        'ButtonOk': 'OK',
        'ButtonKeep': 'Keep both',
        'FileReplaceTitle': 'Replace file',
        'FileReplaceMessage': 'Do you want to replace the file "{FileName}" or keep both files?',
        'UploadButtonLabel': 'File upload button',

        /* Meeting strings */
        'ThereAreNoMeetingsToShow': 'You have no meetings to show.',
        'TheMeetingIsBeingArchived': 'The selected meeting is being archived, details will be available shortly.',
        'TheMeetingIsNotAvailable': 'The requested meeting is not available or has been archived.',

        /* MeetingList strings */
        'NextMeetings': 'Next',
        'CelebratedMeetings': 'Celebrated',
        'ArchivedMeetings': 'Archived',
        'VideoconferenceMeetingList': 'Join',

        /* MeetingStatusBar strings */
        'Videoconference': 'Join the Video Conference',
        'LinkAvailableSoon': 'The link will be available 30 minutes before the start of the meeting',
        'ReserveAgenda': 'Reserve agenda',
        'UrgentNotification': 'Urgent notice',
        'WriteAnUrgentNotification': 'Write a message (maximum 160 characters)',
        'MaximumCharactersForUrgentNotification': 'The message cannot contain more than 160 characters.',
        'DeleteMeeting': 'Delete meeting',
        'CancelMeeting': 'Cancel meeting',
        'StartMeeting': 'Start meeting',
        'StartMeetingprodcEscrito': 'Start prodcedure',
        'StartMeetingRemDocumentacion': 'Agreements and Attendees',
        'FinishMeeting': 'Finish meeting',
        'PublishMeeting': 'Publish',
        'testBookMeeting': 'Reserve agenda',
        'ArchiveMeeting': 'Archive',
        'SendUpdatesToAllAttendees': 'Send updates to all meeting attendees',
        'ThereAreNoUpdatesToSend': 'No updates to send',
        'QuestionToDeleteTheMeeting': 'Are you sure you want to delete this meeting?',
        'QuestionToCancelTheMeeting': 'Are you sure you want to cancel this meeting?',
        'QuestionToFinishTheMeeting': 'Are you sure you want to finish this meeting?',
        'QuestionToPublishTheMeeting': 'Are you sure you want to publish this meeting?',
        'QuestionTotestBookTheMeeting': 'Are you sure you want to book this meeting on the agenda?',
        'QuestionToStartTheMeeting': 'Are you sure you want to start this meeting?',
        'QuestionToArchiveTheMeeting': 'Are you sure you want to archive this meeting?',
        'UpdateMeeting': 'Update meeting',
        'FirstPhraseToUpdateTheMeeting': 'Below, the pending modifications are shown of meeting',
        'SecondPhraseToUpdateTheMeeting': 'that will be applied when you testss the \'Update\' button.',
        'BasicData': 'Basic data',
        'NewTitle': 'Title',
        'NewLocation': 'Location',
        'NewLocationInformation': 'Location detail',
        'NewMeetingType': 'Meeting type',
        'NewDescription': 'Description',
        'NewStartDate': 'Start date',
        'NewEndDate': 'End date',
        'NewOnlineTool': 'Online tool',
        'NewOnlineToolUrl': 'Online tool url',
        'TheOrderOfTheDayHasBeenUpdated': 'The order of the day has been updated.',
        'AddedAssistants': 'Added assistants',
        'RemovedAssistants': 'Removed assistants',
        'EditTheMeetingDetails': 'Edit the meeting details',
        'SeeTheMeetingDetails': 'See the meeting details',

        /* MeetingVoting strings */
        'Vote': 'Vote',
        'ShowQRCode': 'Show QR code',
        'ManagingResults': 'Manage results',
        'ViewResults': 'View results',
        'LoadingVotes': 'Loading votes',
        'VotingPanel': 'Panel of retestsentatives',
        'StartVoting': 'Start voting',
        'NoVotesToDisplay': 'There are no decisive points to vote on.',
        'VotingNotStarted': 'The voting has not started yet.',
        'Approdve': 'In favor',
        'Reject': 'Against',
        'Pending': 'Abstention',
        'Abstention': 'Pending',
        'StartTheVotingPeriod': 'Start the voting period',
        'ListOfVoters': 'List of voters',
        'DescriptionOfStartingTheVotingPeriod': 'The following users will be able to vote at the start of the voting period',
        'DescriptionOfTheVotingPeriodStarted': 'The following users will be able to vote',
        'ShowNoVotes': 'There are no voters',
        'Update': 'Update',
        'MeetingVotingClose': 'Close',
        'ErrorToCreateQRCode': 'Error to create QR code',
        'QRCode': 'QR code',
        'GeneratingTheQRCode': 'Generating the QR code',
        'MeetingVotingMustSelectOption': 'You must select an option.',
        'DeselectOption': 'Deselect option',
        'ConfirmVote': 'Confirm vote',
        'ConfirmChosenOption': 'Confirm the chosen option',
        'Back': 'Back',
        'SubmitVote': 'Submit vote',
        'Members': 'Members',
        'Conveners': 'Conveners',
        'Member': 'Member',
        'Convener': 'Convener',
        'NoPermissionToVote': 'You do not have permission to vote in this meeting.',
        'VoteAlreadyRegisteredByTheUser': 'You have already registered your vote. The selected option is',
        'ContactToChangeYourVote': 'If you wish to change your vote, please contact the Secretariat of the Organ..',
        'CloseVoting': 'Voting ended',
        'CloseVotingVote': 'Voting ended, you have voted: ',
        'CloseVotingNoVote': 'Voting ended, you have not voted',
        'StartingTheVotingPeriod': 'Starting the voting period',
        'SavingChanges': 'Saving changes made, this may take a few moments...',
        'SendingVote': 'Sending your vote',
        'VotingHasEndedAndYouDidNotVote': 'The voting period has ended.',
        'testsidenciaLabel': 'testsidency',
        'VotingStatusTitle': 'Voting result',
        'FinishedStatus': 'Finished',
        'FinishVotationChooseResult': 'To finish the voting on this item, please select the result:',
        
        /* MeetingPoints strings */
        'DeleteTheOrderOfTheDay': 'Delete order of the day',
        'DoYouWantToDeleteTheOrderOfTheDay': 'Do you want to delete the order of the day ',
        'Title': 'Title',
        'Description': 'Description',
        'DownloadTheOrderOfTheDay': 'Download the order of the day',
        'AddPointOfTheOrderOfTheDay': 'Add point of the order of the day',
        'DeleteAssociatedDoc': 'Do you want to detach the document ',
        'ErrorTitleRequired': 'The Title field is required',
        'ErrorDurationRequired': 'Duration field is required',
        'ErrorDuration': 'Only values ​​greater than 0 are allowed',
        'DeleteAssociation': 'Delete association',
        'FromTheOrderOfTheDay': 'from the order of the day',
        'ThereAreNoPointsToShow': 'There are no points of the order of the day to show.',
        'LoadingPoint': 'Loading the points of the order of the day',
        'ReorderItems': 'Reorder',
        'AddSubPoint': 'Add subpoint',
        'ReorderInfoMessage': 'Reorder agenda items',
        'UpSameLevel': 'Raise same level',
        'DownSameLevel': 'Lower same level',
        'prodmoteDifferentLevel': 'Level up',
        'DecreaseDifferentLevel': 'Downgrade',
        'CancelReorderModeMessage': 'Are you sure you want to cancel the reordering you made?',
        'DiscardChangesTitle': 'Cancel changes made',
        'CancelOrdenation': 'Cancel sort',
        'SaveOrdenation': 'Save sort',
        'SaveChangesMade': 'Save changes made',
        'SaveChangesMessage': 'Do you want to save the changes made to the agenda ordering?',
        "TooltipMessageFirstElement": "Not available on the first element of a level",
        "TooltipMessageLastElement": "Not available on the last element of a level",
        "TooltipMessageTopElementIsDecisive": "Not available when its superior element is decisive",
        "TooltipMessageWithoutTopElements": "Not available when there is no superior level",
        "TooltipMessageNoSubordersInDecisiveElements": "Not available on decisive orders",
        "TooltipMessageNoDeleteElementoWithSuborders": "Not available on orders with suborders",
        "TooltipMessageMaxLevel": "The limit of sublevels has been reached",

        /* MeetingDocs strings */
        'Home': 'Home',
        'GeneralOfTheMeeting': 'General of the meeting',
        'AddDocument': 'Add document',
        'RefreshDocuments': 'Refresh documents',
        'NoLabel': 'None',
        'SignedLabel': 'This document is signed, so a label cannot be applied',
        'NoAvailableToLabel': 'Not applicable',
        'ExternalLabelTooltip': 'This document cannot be converted to PDF when published, so it is recommended to delete it and upload it without external labeling',
        'ExternalLabel': 'External label',
        'LabelOnprocess': 'The label is currently being applied',
        'LabelApplied': 'This document has a label applied',
        'NoLabelApplied': 'The document is not labeled',
        'UpdatingDocumentLabel': 'Apply label to document',
        'DocumentLabel': 'Document',
        'TagLabel': 'Label',
        'AreYouSure': 'Are you sure you want to apply this change?',
        'DocHasOtherError': 'The document is not compatible with labels',

        /* MeetingAssistants strings */
        'Pending': 'Pending',
        'Accepted': 'Accepted',
        'Refused': 'Refused',
        'Delegated': 'Delegated',
        'RefusedAndDelegated': 'Refused and Delegated',
        'NotSummoned': 'Not summoned',
        'AttendeesList': 'Attendees list',
        'AddAssistant': 'Add assistant',
        'AddAUser': 'Add a user',
        'ThereAreNoAssistanceToShow': 'There are no attendees to show.',
        'UserAlreadyAdded': 'The user you entered is already added',
        'UserRequired': 'A user must be selected to be added',
        'DownloadTheAttendanceReport': 'Download the attendance report',
        'CheckTheUsersWhoAttendedTheMeeting': 'Check the users who attended the meeting',
        'UserPendingApprodval': 'Pending approdval',
        'ReportAttendance': 'Report attendance',
        'CancelAttendance': 'Cancel attendance',
        'CancelAttendanceText': 'The following user will be canceled from attending the meeting:',
        'LoadingAttendees': 'Loading the assistants',
        'AttendanceDelegation': 'Delegation of attendance',
        'VoteDelegation': 'Delegation of vote',
        'FailedToReportAssistance': 'Failed to report attendance, please try again later',

        /* MeetingAgreements strings */
        'LoadingTheAgreements': 'Loading the agreements',
        'NoAgreementsAvailable': 'There are no agreements to show.',
        'SelectAll': 'Select all',
        'DownloadCertification': 'Download certification',
        'WriteATitle': 'Write a title',
        'WriteADescription': 'Write a description',
        'RequestCertificate': 'Request certificate',
        'CertificateRequestQuestion': 'Do you want to request the certificate of the agreement',
        'AssociateSignedCertificate': 'Associate signed certificate',
        'CertificateAlreadyRequested': 'The certificate of this agreement has already been requested',

        /* MeetingMinutes strings */
        'LoadingTheMinuteSections': 'Loading the minutes',
        'NoMinuteSectionsAvailable': 'There is no minutes to show.',
        'WriteANote': 'Write a note',
        'WriteAComment': 'Write a comment',
        'ViewMinutes': 'View minutes',
        'RequestModificationOfTheMinutes': 'Request modification of the minutes',
        'DownloadMinutes': 'Download minutes template',
        'AssociateMinutes': 'Associate minutes',
        'StatusApprodvalMinutes': 'Minute approdval status',
        'ApprodvalsAccepted': 'Accepted',
        'ApprodvalsPendingModification': 'Modification requests',
        'ApprodvalsRejected': 'Rejected',
        'ApprodvalsPendings': 'Pending',
        'ValidationPeriod': 'The validation period ends on ',
        'RequestApprodveMinutes': 'Request approdval of minutes',
        'RequestApprodveMinutesText': 'Are you sure you want to start the process of approdving the minutes?',
        'ApprodveMinutes': 'Approdval of minutes',
        'AttendanceDialogTitle': 'Approdvers of the minutes',
        'AttendanceDialogDescription': 'The minutes to be associated will be approdved by those attending the call.',
        'AttendanceDialogClarification': 'You can report attendance at the call from the "Attendees" tab.',
        'AttendanceDialogNoItems': 'No user attendance has been reported.',
        'MoreDetailMinutes': 'More detail...',
        'DetailMinutesTitle': 'Approdval status detail',

        /* MeetingNew strings */
        'CreateConvo': 'Create convo',
        'OnlineToolLabel': 'Online Tool Options',
        'PlaceholderDescription': 'Please, configure the web part',
        'PlaceholderIconText': 'Configure the web part',
        'PlaceholderButtonLabel': 'Configure',
        'AtendanceTypeLabel': 'Attendance type',
        'TermGroupLabel': 'Term group (Id)',
        'TitlePlaceholder': 'Add a title',
        'StartDatePlaceholder': 'Start',
        'EndDatePlaceholder': 'End',
        'LocationPlaceholder': 'Add a location',
        'OnlineLabel': 'Online call',
        'LocationDescriptionPlaceholder': 'Add additional information to the location',
        'OnlineToolPlaceholder': 'Select a tool',
        'AttendanceTypePlaceholder': 'Select attendance type',
        'UrlPlaceholder': 'Reúnete call link',
        'PeoplePlaceholder': 'members (con voto)',
        'DescriptionPlaceholder': 'Enter the details of the call',
        'NewConvo': 'New convo',
        'RequiredField': 'Required field.',
        'MinimumCharactersForTitle': 'Title must be a minimum of 2 characters.',
        'MaximumCharactersForTitle': 'Title must be a maximum of 255 characters.',
        'MaximumCharactersForDescription': 'Description must be a maximum of 1500 characters.',
        'StartDateLessThanTheCurrentDate': 'The start date cannot be less than the current date.',
        'EndDateLessThanStartDate': 'The end date cannot be less than the start date.',
        'MaximumCharactersForLocation': 'Location must be a maximum of 255 characters.',
        'MaximumCharactersForLocationDetails': 'Location details must be a maximum of 255 characters.',
        'RequiredUrl': 'A link is required.',
        'RequiredValidUrl': 'Enter a valid link.',
        'MaximumCharactersForUrl': 'Link must be a maximum of 255 characters.',
        'RequiredAttendanceTypeId': 'It is required to choose the type of assistance.',
        'RequiredAttendees': 'It is required to indicate at least one person.',
        'GuestPeoplePlaceholder': 'Asistentes (sin voto)',
        'Saving': 'Saving',

        /* MeetingForm strings */
        'EditMeeting': 'Edit meeting',
        'NewMeeting': 'New meeting',
        'MeetingDetails': 'Meeting details',

        /* NewDocForm strings */
        'Document': 'Document',
        'SelectADocument': 'Select a document',
        'SelectingADocumentIsRequired': 'You must select a document to associate it.',
        'AssociateTo': 'Associate to'
    }
});