define([], function () {
  return {
    /* General strings */
    'MeetingPoints': 'Orden del día',
    'Assistants': 'Asistentes',
    'Documents': 'Documents',
    'Agreements': 'Acuerdos',
    'Minutes': 'Minutes',
    'No': 'No',
    'Yes': 'Sí',
    'RuleOut': 'Descartar',
    'Close': 'Cerrar',
    'Cancel': 'Cancelar',
    'Delete': 'Eliminar',
    'Edit': 'Editar',
    'Replace': 'Reemplazar',
    'Reselect': 'Volver a seleccionar',
    'Accept': 'Aceptar',
    'Save': 'Guardar',
    'Send': 'Enviar',
    'Upload': 'Subir',
    'Publish': 'Publicar',
    'Create': 'Crear',
    'Request': 'Solicitar',
    'LookFor': 'Buscar',
    'Visualize': 'Visualizar',
    'Archive': 'Archivar',
    'AssociateDocument': 'Asociar Document',
    'Loading': 'Cargando',
    'Deleting': 'Eliminando',
    'Canceling': 'Cancelando',
    'Publishing': 'Publicando',
    'Sending': 'Enviando',
    'Requesting': 'Solicitando',
    'CommentRequired': 'Debe escribir un comentario.',
    'MessageRequired': 'Debe escribir un mensaje.',
    'BackendErrorMessage': 'Se ha prodducido un error, vuelva a intentarlo más tarde.',
    'SendUpdate': 'Enviar actualización',
    'SendingUpdate': 'Enviando actualización',
    'Attendance': 'Attendance',
    'Certification': 'Certificación',
    'Online': 'Online',
    'InPerson': 'InPerson',

    /* MeetingWebPart strings */
    'NoResultsFound': 'No se han encontrado resultados.',
    'ShowMoreSubtitle': 'Ver más',
    'FailUploadFile': 'Error al cargar el archivo.',
    'CancelUploadFile': 'Descartar archivo',
    'ButtonUploadFile': 'Subir archivos',
    'MaximumFilesTitle': 'Número máximo de archivos',
    'MaximumFilesMessage': 'Lo sentimos, la cantidad máxima de archivos que puedes subir a la vez es {MaxNumber}. ¿Quieres subir los {MaxNumber} primeros archivos o volver a seleccionarlos?',
    'MaximumFileSizeTitle': 'Tamaño máximo del archivo',
    'MaximumFileSizeMessage': 'Lo sentimos, el tamaño máximo de archivo para subir es {FileSize}. El tamaño del archivo "{FileName}" es {FileSize}.',
    'FileTypeTitle': 'Tipo de archivo',
    'FileTypeMessage': 'Lo sentimos, no se puede subir el formato del archivo "{FileName}".',
    'CheckAgain': 'No volver a mostrar',
    'CheckApplyAll': 'Aplicar a todo',
    'ButtonOk': 'OK',
    'ButtonKeep': 'Mantener ambos',
    'FileReplaceTitle': 'Reemplazar el archivo',
    'FileReplaceMessage': '¿Quieres reemplazar el archivo "{FileName}" o conservar ambos archivos?',
    'UploadButtonLabel': 'Botón de subir archivos',

    /* Meeting strings */
    'ThereAreNoMeetingsToShow': 'No tiene Meetings para mostrar.',
    'TheMeetingIsBeingArchived': 'La Meeting seleccionada se está archivando, los detalles estarán disponibles en unos instantes.',
    'TheMeetingIsNotAvailable': 'La Meeting solicitada no está disponible o ha sido archivada.',

    /* MeetingList strings */
    'NextMeetings': 'Próximas',
    'CelebratedMeetings': 'Celebradas',
    'ArchivedMeetings': 'Archivadas',
    'VideoconferenceMeetingList': 'Unirse',

    /* MeetingStatusBar strings */
    'Videoconference': 'Unirse a la Videoconferencia',
    'LinkAvailableSoon': 'El enlace estará disponible 30 minutos antes del comienzo de la reunión',
    'ReserveAgenda': 'Reservar agenda',
    'UrgentNotification': 'Alert Urgent',
    'WriteAnUrgentNotification': 'Escriba un mensaje (máximo 160 caracteres)',
    'MaximumCharactersForUrgentNotification': 'El mensaje no puede contener más de 160 caracteres.',
    'DeleteMeeting': 'Eliminar Meeting',
    'CancelMeeting': 'Cancelar Meeting',
    'StartMeeting': 'Iniciar reunión',
    'StartMeetingprodcEscrito': 'Iniciar prodcedimiento',
    'StartMeetingRemDocumentacion': 'Acuerdos y Asistentes',
    'FinishMeeting': 'Finalizar Meeting',
    'PublishMeeting': 'Publicar',
    'testBookMeeting': 'Reservar agenda',
    'ArchiveMeeting': 'Archivar',
    'SendUpdatesToAllAttendees': 'Enviar actualizaciones a todos los asistentes de la Meeting',
    'ThereAreNoUpdatesToSend': 'No hay actualizaciones para enviar',
    'QuestionToDeleteTheMeeting': '¿Estás seguro de que quieres eliminar esta Meeting?',
    'QuestionToCancelTheMeeting': '¿Estás seguro de que quieres cancelar esta Meeting?',
    'QuestionToFinishTheMeeting': '¿Estás seguro de que quieres finalizar esta Meeting?',
    'QuestionToPublishTheMeeting': '¿Estás seguro de que quieres publicar esta Meeting?',
    'QuestionTotestBookTheMeeting': '¿Estás seguro de que quieres reservar en la agenda esta Meeting?',
    'QuestionToStartTheMeeting': '¿Estás seguro de que quieres iniciar esta Meeting?',
    'QuestionToArchiveTheMeeting': '¿Estás seguro de que quieres archivar esta Meeting?',
    'UpdateMeeting': 'Actualizar Meeting',
    'FirstPhraseToUpdateTheMeeting': 'A continuación, se muestran las modificaciones pendientes de la Meeting',
    'SecondPhraseToUpdateTheMeeting': 'que se aplicarán al pulsar el botón \'Actualizar\'.',
    'BasicData': 'Datos básicos',
    'NewTitle': 'Título',
    'NewLocation': 'Ubicación',
    'NewLocationInformation': 'Detalle de la ubicación',
    'NewMeetingType': 'Tipo de reunión',
    'NewDescription': 'Descripción',
    'NewStartDate': 'Fecha de inicio',
    'NewEndDate': 'Fecha de fin',
    'NewOnlineTool': 'Herramienta online',
    'NewOnlineToolUrl': 'Url de la herramienta online',
    'TheOrderOfTheDayHasBeenUpdated': 'Se ha actualizado el orden del día.',
    'AddedAssistants': 'Asistentes añadidos',
    'RemovedAssistants': 'Asistentes eliminados',
    'EditTheMeetingDetails': 'Editar los detalles de la Meeting',
    'SeeTheMeetingDetails': 'Ver los detalles de la Meeting',

    /* MeetingVoting strings */
    'Vote': 'Votar',
    'ShowQRCode': 'Mostrar código QR',
    'ManagingResults': 'Gestionar resultados',
    'ViewResults': 'Visualizar resultados',
    'LoadingVotes': 'Cargando las Votes',
    'VotingPanel': 'Panel de retestsentantes',
    'StartVoting': 'Iniciar Votes',
    'NoVotesToDisplay': 'No hay puntos decisorios para votar.',
    'VotingNotStarted': 'La votación todavía no se ha iniciado.',
    'Approdve': 'A favor',
    'Reject': 'En contra',
    'Pending': 'Pendiente',
    'Abstention': 'Abstención',
    'StartTheVotingPeriod': 'Iniciar el período de votación',
    'ListOfVoters': 'Listado de votantes',
    'DescriptionOfStartingTheVotingPeriod': 'Los siguientes usuarios podrán votar al iniciar el período de votación',
    'DescriptionOfTheVotingPeriodStarted': 'Los siguientes usuarios podrán votar',
    'ShowNoVotes': 'No hay votantes',
    'Update': 'Actualizar',
    'MeetingVotingClose': 'Cerrar',
    'ErrorToCreateQRCode': 'Error al crear el código QR',
    'QRCode': 'Código QR',
    'GeneratingTheQRCode': 'Generando el código QR',
    'MeetingVotingMustSelectOption': 'Debe seleccionar una opción.',
    'DeselectOption': 'Deseleccionar opción',
    'ConfirmVote': 'Confirmar voto',
    'ConfirmChosenOption': 'Confirme la opción elegida',
    'Back': 'Atrás',
    'SubmitVote': 'Enviar voto',
    'Members': 'members',
    'Conveners': 'schedulers',
    'Member': 'Miembro',
    'Convener': 'Convocante',
    'NoPermissionToVote': 'No tienes permiso para votar en esta Meeting.',
    'VoteAlreadyRegisteredByTheUser': 'Ya ha registrado su voto. La opción seleccionada es',
    'ContactToChangeYourVote': 'Si desea modificar su voto, contacte con la Secretaría del Órgano.',
    'CloseVoting': 'Votación finalizada',
    'CloseVotingVote': 'Votación finalizada, ha votado: ',
    'CloseVotingNoVote': 'Votación finalizada, no ha votado',
    'StartingTheVotingPeriod': 'Iniciando el período de votación',
    'SavingChanges': 'Guardando los cambios realizados, esto puede tomar unos instantes...',
    'SendingVote': 'Enviando su voto',
    'VotingHasEndedAndYouDidNotVote': 'El periodo de votación ha finalizado.',
    'testsidenciaLabel': 'testsidencia',
    'VotingStatusTitle': 'Resultado de la votación',
    'FinishedStatus': 'Finalizado',
    'FinishVotationChooseResult': 'Para finalizar la votación de este punto, por favor seleccione el resultado:',

    /* MeetingPoints strings */
    'DeleteTheOrderOfTheDay': 'Eliminar orden del día',
    'DoYouWantToDeleteTheOrderOfTheDay': '¿Desea eliminar el orden del día ',
    'Title': 'Título',
    'Description': 'Descripción',
    'DownloadTheOrderOfTheDay': 'Descargar el orden del día',
    'AddPointOfTheOrderOfTheDay': 'Añadir punto del orden del día',
    'DeleteAssociatedDoc': '¿Desea desasociar el Document ',
    'ErrorTitleRequired': 'El campo Título es obligatorio',
    'ErrorDurationRequired': 'El campo Duración es obligatorio',
    'ErrorDuration': 'Solo se permiten valores superiores a 0',
    'DeleteAssociation': 'Eliminar asociación',
    'FromTheOrderOfTheDay': 'del orden del día',
    'ThereAreNoPointsToShow': 'No hay puntos del orden del día para mostrar.',
    'LoadingPoint': 'Cargando los puntos del orden del día',
    'ReorderItems': 'Reordenar',
    'AddSubPoint': 'Añadir subpunto',
    'ReorderInfoMessage': 'Reordene los puntos de orden del día',
    'UpSameLevel': 'Subir en el mismo nivel',
    'DownSameLevel': 'Bajar en el mismo nivel',
    'prodmoteDifferentLevel': 'Ascender de nivel',
    'DecreaseDifferentLevel': 'Descender de nivel',
    'CancelReorderModeMessage': 'Los cambios realizados no serán aplicados. ¿Está seguro de realizar esta acción?',
    'DiscardChangesTitle': 'Deshacer cambios realizados',
    'CancelOrdenation': 'Deshacer ordenación',
    'SaveOrdenation': 'Guardar ordenación',
    'SaveChangesMade': 'Guardar cambios realizados',
    'SaveChangesMessage': '¿Quieres guardar los cambios realizados en la ordenación del orden del día?',
    'TooltipMessageFirstElement': 'No disponible sobre el primer elemento de un nivel',
    'TooltipMessageLastElement': 'No disponible sobre el último elemento de un nivel',
    'TooltipMessageTopElementIsDecisive': 'No disponible cuando su elemento superior es decisivo',
    'TooltipMessageWithoutTopElements': 'No disponible cuando no existe un nivel superior',
    'TooltipMessageNoSubordersInDecisiveElements': 'No disponible sobre órdenes decisorias',
    'TooltipMessageNoDeleteElementoWithSuborders': 'No disponible sobre órdenes con subpuntos',
    'TooltipMessageMaxLevel': 'Se ha alcanzado el límite de subniveles',

    /* MeetingDocs strings */
    'Home': 'Inicio',
    'GeneralOfTheMeeting': 'General de la Meeting',
    'AddDocument': 'Añadir Document',
    'RefreshDocuments': 'Actualizar Documents',
    'NoLabel': 'Ninguna',
    'SignedLabel': 'Este Document está firmado, por lo que no puede aplicarse una etiqueta',
    'NoAvailableToLabel': 'No aplicable',
    'ExternalLabelTooltip': 'Este Document no puede ser convertido a PDF cuando se publique, por tanto, se recomenda eliminar el Document y subirlo sin etiquetado externo',
    'ExternalLabel': 'Etiqueta externa',
    'LabelOnprocess': 'La etiqueta se está aplicando en estos momentos',
    'LabelApplied': 'Este Document tiene una etiqueta aplicada',
    'NoLabelApplied': 'El Document no está etiquetado',
    'UpdatingDocumentLabel':'Aplicar etiqueta al Document',
    'DocumentLabel':'Document',
    'TagLabel': 'Etiqueta',
    'AreYouSure': '¿Estás seguro de aplicar este cambio?',
    'DocHasOtherError': 'El Document no es compatible con las etiquetas',

    /* MeetingAssistants strings */
    'Pending': 'Pendiente',
    'Accepted': 'Aceptado',
    'Refused': 'Rechazado',
    'Delegated': 'Delegado',
    'RefusedAndDelegated': 'Rechazado y Delegado',
    'NotSummoned': 'No convocado',
    'AttendeesList': 'Listado de asistentes',
    'AddAssistant': 'Añadir asistente',
    'AddAUser': 'Agregue un usuario',
    'ThereAreNoAssistanceToShow': 'No hay asistentes para mostrar.',
    'UserAlreadyAdded': 'El usuario que ha introducido ya está agregado',
    'UserRequired': 'Se debe seleccionar un usuario para agregarlo',
    'DownloadTheAttendanceReport': 'Descargar el informe de Attendance',
    'CheckTheUsersWhoAttendedTheMeeting': 'Marque los usuarios que hayan asistido a la reunión',
    'UserPendingApprodval': 'Pendiente de aprodbación',
    'ReportAttendance': 'Informar Attendance',
    'CancelAttendance': 'Cancelar Attendance',
    'CancelAttendanceText': 'Se cancelará la Attendance a la reunión del siguiente usuario:',
    'LoadingAttendees': 'Cargando los asistentes',
    'AttendanceDelegation': 'Delegación de Attendance',
    'VoteDelegation': 'Delegación de voto',
    'FailedToReportAssistance': 'No se ha podido informar la Attendance, vuelva a intentarlo más tarde',

    /* MeetingAgreements strings */
    'LoadingTheAgreements': 'Cargando los acuerdos',
    'NoAgreementsAvailable': 'No hay acuerdos para mostrar.',
    'SelectAll': 'Seleccionar todos',
    'DownloadCertification': 'Descargar certificación',
    'WriteATitle': 'Escriba un título',
    'WriteADescription': 'Escriba una descripción',
    'RequestCertificate': 'Solicitar certificado',
    'CertificateRequestQuestion': '¿Quieres solicitar el certificado del acuerdo',
    'AssociateSignedCertificate': 'Asociar certificado firmado',
    'CertificateAlreadyRequested': 'Ya se ha solicitado el certificado de este acuerdo',

    /* MeetingMinutes strings */
    'LoadingTheMinuteSections': 'Cargando el Minutes',
    'NoMinuteSectionsAvailable': 'No hay un Minutes para mostrar.',
    'WriteANote': 'Escriba una nota',
    'WriteAComment': 'Escriba un comentario',
    'ViewMinutes': 'Visualizar Minutes',
    'RequestModificationOfTheMinutes': 'Solicitar modificación del Minutes',
    'DownloadMinutes': 'Descargar plantilla Minutes',
    'AssociateMinutes': 'Asociar Minutes',
    'StatusApprodvalMinutes': 'Estado aprodbación Minutes',
    'ApprodvalsAccepted': 'Aprodbaciones',
    'ApprodvalsPendingModification': 'Requestes de modificación',
    'ApprodvalsRejected': 'Rechazos',
    'ApprodvalsPendings': 'Pendientes',
    'ValidationPeriod': 'El periodo de validación finaliza el ',
    'RequestApprodveMinutes': 'Solicitar aprodbación Minutes',
    'RequestApprodveMinutesText': '¿Estás seguro de que quieres iniciar el prodceso de aprodbación del Minutes?',
    'ApprodveMinutes': 'Aprodbación de Minutes',
    'AttendanceDialogTitle': 'Aprodbación del Minutes',
    'AttendanceDialogDescription': 'El Minutes a asociar será aprodbada por los siguientes Attendees of la Meeting.',
    'AttendanceDialogClarification': 'Para actualizar esta información, puede informar la Attendance a la Meeting desde la pestaña de "Asistentes".',
    'AttendanceDialogNoItems': 'No se ha informado la Attendance de ningun usuario.',
    'MoreDetailMinutes': 'Más detalle...',
    'DetailMinutesTitle': 'Detalle de estado de aprodbación',

    /* MeetingNew strings */
    'CreateConvo': 'Crear Meeting',
    'OnlineToolLabel': 'Opciones Herramienta online',
    'PlaceholderDescription': 'Por favor, configure el web part',
    'PlaceholderIconText': 'Configure el web part',
    'PlaceholderButtonLabel': 'Configurar',
    'AtendanceTypeLabel': 'Tipo de Attendance',
    'TermGroupLabel': 'Grupo de términos (Id)',
    'TitlePlaceholder': 'Agregue un título',
    'StartDatePlaceholder': 'Inicio',
    'EndDatePlaceholder': 'Fin',
    'LocationPlaceholder': 'Agregue una ubicación',
    'OnlineLabel': 'Meeting en línea',
    'LocationDescriptionPlaceholder': 'Agregue información adicional a la ubicación',
    'OnlineToolPlaceholder': 'Seleccione una herramienta',
    'AttendanceTypePlaceholder': 'Seleccione tipo de Attendance',
    'UrlPlaceholder': 'Vínculo Meeting Reúnete',
    'PeoplePlaceholder': 'members (con voto)',
    'DescriptionPlaceholder': 'Escriba los detalles de la Meeting',
    'NewConvo': 'Nueva Meeting',
    'RequiredField': 'Campo obligatorio.',
    'MinimumCharactersForTitle': 'El título debe tener un mínimo de 2 caracteres.',
    'MaximumCharactersForTitle': 'El título debe tener un máximo 255 caracteres.',
    'MaximumCharactersForDescription': 'La descripción debe tener un máximo de 1500 caracteres.',
    'StartDateLessThanTheCurrentDate': 'La fecha de inicio no puede ser menor que la fecha actual.',
    'EndDateLessThanStartDate': 'La fecha de fin no puede ser menor que la fecha de inicio.',
    'MaximumCharactersForLocation': 'La ubicación debe tener un máximo de 255 caracteres.',
    'MaximumCharactersForLocationDetails': 'Los detalles de la ubicación deben tener un máximo de 255 caracteres.',
    'RequiredUrl': 'Es obligatorio introducir un enlace.',
    'RequiredValidUrl': 'Introduzca un enlace válido.',
    'MaximumCharactersForUrl': 'El enlace debe tener un máximo de 255 caracteres.',
    'RequiredAttendanceTypeId': 'Es obligatorio elegir el tipo de Attendance.',
    'RequiredAttendees': 'Es obligatorio indicar al menos una persona.',
    'GuestPeoplePlaceholder': 'Asistentes (sin voto)',
    'Saving': 'Guardando',

    /* MeetingForm strings */
    'EditMeeting': 'Editar Meeting',
    'NewMeeting': 'Nueva Meeting',
    'MeetingDetails': 'Detalles Meeting',

    /* NewDocForm strings */
    'Document': 'Document',
    'SelectADocument': 'Seleccione un Document',
    'SelectingADocumentIsRequired': 'Debe seleccionar un Document para asociarlo.',
    'AssociateTo': 'Asociar a'
  }
});