define([], function () {
    return {
        /* General strings */
        'MeetingPoints': 'Eguneko ordena',
        'Assistants': 'Laguntzaileak',
        'Documents': 'Dokumentuak',
        'Agreements': 'Hitzarmenak',
        'Minutes': 'Aktak',
        'No': 'Ez',
        'Yes': 'Bai',
        'RuleOut': 'Baztertu',
        'Close': 'Itxi',
        'Cancel': 'Utzi',
        'Delete': 'Ezabatu',
        'Edit': 'Editatu',
        'Replace': 'Ordezkatu',
        'Reselect': 'Hautatu berriro',
        'Accept': 'Onartu',
        'Save': 'Gorde',
        'Send': 'Igorri',
        'Upload': 'Kargatu',
        'Publish': 'Argitalpena',
        'Create': 'Sortu',
        'Request': 'Eskaera',
        'LookFor': 'Bilatu',
        'Visualize': 'Ikusi',
        'Archive': 'Artxiboa',
        'AssociateDocument': 'Elkartu dokumentua',
        'Loading': 'Kargatzen',
        'Deleting': 'Kenduz',
        'Canceling': 'Bertan behera uzten',
        'Publishing': 'Argitaratzea',
        'Sending': 'Bidaltzen',
        'Requesting': 'Eskatzen',
        'CommentRequired': 'Iruzkin bat idatzi behar duzu.',
        'MessageRequired': 'Mezu bat idatzi behar duzu.',
        'BackendErrorMessage': 'Errore bat gertatu da, mesedez berriro saiatu geroago.',
        'SendUpdate': 'Bidali eguneratzea',
        'SendingUpdate': 'Eguneratzea bidaltzen',
        'Attendance': 'Asistentzia',
        'Certification': 'Ziurtapena',
        'Online': 'Online',
        'InPerson': 'Pertsonalki',

        /* MeetingWebPart strings */
        'NoResultsFound': 'Ez da emaitzarik aurkitu.',
        'ShowMoreSubtitle': 'Gehiago ikusi',
        'FailUploadFile': 'Errorea fitxategia kargatzean.',
        'CancelUploadFile': 'Baztertu fitxategia',
        'ButtonUploadFile': 'Kargatu fitxategiak',
        'MaximumFilesTitle': 'Fitxategien gehienezko kopurua',
        'MaximumFilesMessage': 'Barkatu, aldi berean kargatu ditzakezun gehienezko fitxategi kopurua {MaxNumber} da. Lehenengo {MaxNumber} fitxategiak kargatu edo berriro hautatu nahi dituzu?',
        'MaximumFileSizeTitle': 'Fitxategiaren gehienezko tamaina',
        'MaximumFileSizeMessage': 'Barkatu, kargatzeko fitxategiaren gehienezko tamaina {FileSize} da. "{FileName}" fitxategiaren tamaina {FileSize} da.',
        'FileTypeTitle': 'Fitxategi mota',
        'FileTypeMessage': 'Barkatu, ezin da "{FileName}" fitxategi-formatua kargatu.',
        'CheckAgain': 'Ez berriro erakutsi',
        'CheckApplyAll': 'Aplikatu guztiari',
        'ButtonOk': 'OK',
        'ButtonKeep': 'Mantendu biak',
        'FileReplaceTitle': 'Ordeztu fitxategia',
        'FileReplaceMessage': '"{FileName}" fitxategia ordeztu edo bi fitxategiak mantendu nahi dituzu?',
        'UploadButtonLabel': 'Fitxategia igotzeko botoia',

        /* Meeting strings */
        'ThereAreNoMeetingsToShow': 'Ez duzu deirik erakusteko.',
        'TheMeetingIsBeingArchived': 'Hautatutako deia artxibatzen ari da, xehetasunak laster egongo dira eskuragarri.',
        'TheMeetingIsNotAvailable': 'Eskatutako deia ez dago erabilgarri edo artxibatu egin da.',

        /* MeetingList strings */
        'NextMeetings': 'Hurrengo',
        'CelebratedMeetings': 'Ospatua',
        'ArchivedMeetings': 'Artxibatuta',
        'VideoconferenceMeetingList': 'Sartu',

        /* MeetingStatusBar strings */
        'Videoconference': 'Sartu Bideo Jardunaldira',
        'LinkAvailableSoon': 'Esteka bilera hasi baino 30 minutu lehenago egongo da eskuragarri',
        'ReserveAgenda': 'Erreserba agenda',
        'UrgentNotification': 'testmiazko oharra',
        'WriteAnUrgentNotification': 'Idatzi mezu bat (gehienez 160 karaktere)',
        'MaximumCharactersForUrgentNotification': 'Mezuak ezin du izan 160 karaktere baino gehiago.',
        'DeleteMeeting': 'Ezabatu bilera',
        'CancelMeeting': 'Utzi bilera',
        'StartMeeting': 'Hasi bilera',
        'StartMeetingprodcEscrito': 'prodzedura hasi',
        'StartMeetingRemDocumentacion': 'Akordioak eta Parte-hartzaileak',
        'FinishMeeting': 'Amaiera bilera',
        'PublishMeeting': 'Argitaratu',
        'testBookMeeting': 'Erreserba agenda',
        'ArchiveMeeting': 'Fitxategia',
        'SendUpdatesToAllAttendees': 'Bidali eguneraketak bilerako parte-hartzaile guztiei',
        'ThereAreNoUpdatesToSend': 'Ez dago eguneratzerik bidaltzeko',
        'QuestionToDeleteTheMeeting': 'Ziur bilera hau ezabatu nahi duzula?',
        'QuestionToCancelTheMeeting': 'Ziur bilera hau bertan behera utzi nahi duzula?',
        'QuestionToFinishTheMeeting': 'Ziur bilera hau amaitu nahi duzula?',
        'QuestionToPublishTheMeeting': 'Ziur dei hau argitaratu nahi duzula?',
        'QuestionTotestBookTheMeeting': 'Ziur deialdi hau agendan gorde nahi duzula?',
        'QuestionToStartTheMeeting': 'Ziur dei hau hasi nahi duzula?',
        'QuestionToArchiveTheMeeting': 'Ziur deia artxibatu nahi duzula?',
        'UpdateMeeting': 'Eguneratu bilera',
        'FirstPhraseToUpdateTheMeeting': 'Jarraian, deialdiaren zain dauden aldaketak daude',
        'SecondPhraseToUpdateTheMeeting': 'hori \'Eguneratu\' botoia sakatzean aplikatuko da.',
        'BasicData': 'Oinarrizko datuak',
        'NewTitle': 'Izenburu',
        'NewLocation': 'Kokapen',
        'NewLocationInformation': 'Kokapenaren xehetasun',
        'NewMeetingType': 'Bilera mota',
        'NewDescription': 'Deskribapen',
        'NewStartDate': 'Hasteko data',
        'NewEndDate': 'Amaiera data',
        'NewOnlineTool': 'Sineko tresna',
        'NewOnlineToolUrl': 'Lineko tresnaren url',
        'TheOrderOfTheDayHasBeenUpdated': 'Eguneko ordena eguneratu da.',
        'AddedAssistants': 'Laguntzaileak gehitu',
        'RemovedAssistants': 'Laguntzaileak kendu',
        'EditTheMeetingDetails': 'Editatu bileraren xehetasunak',
        'SeeTheMeetingDetails': 'Ikusi bileraren xehetasunak',

        /* MeetingVoting strings */
        'Vote': 'Bozkatu',
        'ShowQRCode': 'Erakutsi QR kodea',
        'ManagingResults': 'Kudeatu emaitzak',
        'ViewResults': 'Ikusi emaitzak',
        'LoadingVotes': 'Botoak kargatzen',
        'VotingPanel': 'Ordezkari Batzordea',
        'StartVoting': 'Hasi botoa ematen',
        'NoVotesToDisplay': 'Ez dago erabakitzeko punturik bozkatzeko.',
        'VotingNotStarted': 'Bozketa oraindik ez da hasi.',
        'Approdve': 'Alde',
        'Reject': 'Aurka',
        'Pending': 'Abstentzioa',
        'Abstention': 'Zain',
        'StartTheVotingPeriod': 'Hasi bozkatzeko epea',
        'ListOfVoters': 'Hautesle zerrenda',
        'DescriptionOfStartingTheVotingPeriod': 'Ondorengo erabiltzaileek botoa emateko epearen hasieran eman ahal izango dute',
        'DescriptionOfTheVotingPeriodStarted': 'Hurrengo erabiltzaileek botoa eman ahal izango dute',
        'ShowNoVotes': 'Ez dago boto-emailerik',
        'Update': 'Eguneratu',
        'MeetingVotingClose': 'Itxi',
        'ErrorToCreateQRCode': 'Errore bat gertatu da QR kodea sortzean',
        'QRCode': 'QR kodea',
        'GeneratingTheQRCode': 'QR kodea sortzea',
        'MeetingVotingMustSelectOption': 'Aukera bat hautatu behar duzu.',
        'DeselectOption': 'Deshautatu aukera',
        'ConfirmVote': 'Berretsi botoa',
        'ConfirmChosenOption': 'Berretsi aukeratutako aukera',
        'Back': 'Itzuli',
        'SubmitVote': 'Botoa bidali',
        'Members': 'Kideak',
        'Conveners': 'Deitzaileak',
        'Member': 'Kide',
        'Convener': 'Deitzaile',
        'NoPermissionToVote': 'Ez duzu bilera honetan botoa emateko baimenik.',
        'VoteAlreadyRegisteredByTheUser': 'Zure botoa erregistratuta dago dagoeneko. Aukeratutako aukera hau da',
        'ContactToChangeYourVote': 'Zure botoa aldatu nahi baduzu, jarri harremanetan Departmentaren Idazkaritzarekin.',
        'CloseVoting': 'Botoa amaitu da',
        'CloseVotingVote': 'Botoa amaitu, bozkatu duzu:',
        'CloseVotingNoVote': 'Botoa amaitu da, ez duzu bozkatu',
        'StartingTheVotingPeriod': 'Bozketa epeari hasiera ematea',
        'SavingChanges': 'Egindako aldaketak gordetzen, baliteke une batzuk behar izatea...',
        'SendingVote': 'Zure botoa bidaltzen',
        'VotingHasEndedAndYouDidNotVote': 'Bozketaren epea amaitu da.',
        'testsidenciaLabel': 'Lehendakaritza',
        'VotingStatusTitle': 'Bozketa emaitza',
        'FinishedStatus': 'Amaituta',
        'FinishVotationChooseResult': 'Puntu honen bozketa amaitzeko, aukeratu emaitza:',

        /* MeetingPoints strings */
        'DeleteTheOrderOfTheDay': 'Ezabatu eguneko ordena',
        'DoYouWantToDeleteTheOrderOfTheDay': 'Eguneko ordena ezabatu nahi duzu ',
        'Title': 'Izenburua',
        'Description': 'Deskribapena',
        'DownloadTheOrderOfTheDay': 'Deskargatu eguneko ordena',
        'AddPointOfTheOrderOfTheDay': 'Gehitu eguneko ordenaren puntua',
        'DeleteAssociatedDoc': 'Dokumentua kendu nahi al duzu ',
        'ErrorTitleRequired': 'Izenburua eremua beharrezkoa da',
        'ErrorDurationRequired': 'Iraupena eremua beharrezkoa da',
        'ErrorDuration': '0 baino handiagoak diren balioak soilik onartzen dira',
        'DeleteAssociation': 'Ezabatu elkartea',
        'FromTheOrderOfTheDay': 'eguneko ordenatik',
        'ThereAreNoPointsToShow': 'Ez dago eguneko ordenaren punturik erakusteko.',
        'LoadingPoint': 'Eguneko ordenako puntuak kargatzen',
        'ReorderItems': 'Berrantolatzea',
        'AddSubPoint': 'Gehitu berria',
        'ReorderInfoMessage': 'BBerrantolatu agendako gaiak',
        'UpSameLevel': 'Maila bera igo',
        'DownSameLevel': 'Beheko maila berean',
        'prodmoteDifferentLevel': 'Maila bat gora',
        'DecreaseDifferentLevel': 'Jaitsi',
        "CancelReorderModeMessage": "Ziur zaude egindako aldaketak desegin nahi dituzula?",
        "DiscardChangesTitle": "Egindako aldaketak desegin",
        "CancelOrdenation": "Ordenazioa desegin",
        "SaveOrdenation": "Ordenazioa gorde",
        "SaveChangesMade": "Egindako aldaketak gorde",
        "SaveChangesMessage": "Egunaren ordenaren ordenazioan egindako aldaketak gorde nahi dituzu?",
        "TooltipMessageFirstElement": "Ez dago erabilgarri maila bateko lehenengo elementuan",
        "TooltipMessageLastElement": "Ez dago erabilgarri maila bateko azkeneko elementuan",
        "TooltipMessageTopElementIsDecisive": "Ez dago erabilgarri bere gaineko elementua erabakigarria denean",
        "TooltipMessageWithoutTopElements": "Ez dago erabilgarri gaineko maila bat ez dagoenean",
        "TooltipMessageNoSubordersInDecisiveElements": "Ez dago erabilgarri erabaki-elementuetan",
        "TooltipMessageNoDeleteElementoWithSuborders": "Ez dago erabilgarri azpiaginduak dituen elementuetan",
        "TooltipMessageMaxLevel": "Azpinivelen muga lortu da",

        /* MeetingDocs strings */
        'Home': 'Hasiera',
        'GeneralOfTheMeeting': 'Deialdiaren orokorra',
        'AddDocument': 'Gehitu dokumentua',
        'RefreshDocuments': 'Dokumentuak eguneratu',
        'NoLabel': 'Bat ere ez',
        'SignedLabel': 'Dokumentu hau sinatuta dago, beraz ezin zaio etiketa aplikatu',
        'NoAvailableToLabel': 'Ez da aplikagarria',
        'ExternalLabelTooltip': 'Dokumentu hau ezin da PDF bihurtu argitaratzean, beraz gomendagarria da dokumentua ezabatzea eta kanpo etiketarik gabe berriro igotzea',
        'ExternalLabel': 'Kanpo etiketa',
        'LabelOnprocess': 'Etiketa une honetan aplikatzen ari da',
        'LabelApplied': 'Dokumentu honek etiketa bat aplikatuta dauka',
        'NoLabelApplied': 'Dokumentua ez dago etiketatuta',
        'UpdatingDocumentLabel': 'Etiketa aplikatu dokumentuari',
        'DocumentLabel': 'Dokumentua',
        'TagLabel': 'Etiketa',
        'AreYouSure': 'Ziur zaude aldaketa hau aplikatu nahi duzula?',
        'DocHasOtherError': 'Dokumentua ez da bateragarria etiketekin',

        /* MeetingAssistants strings */
        'Pending': 'Belarritakoa',
        'Accepted': 'Onartua',
        'Refused': 'Ezezkoa',
        'Delegated': 'Delegatua',
        'RefusedAndDelegated': 'Ezezkoa eta Delegatua',
        'NotSummoned': 'Ez deituta',
        'AttendeesList': 'Bertaratutakoen zerrenda',
        'AddAssistant': 'Gehitu laguntzailea',
        'AddAUser': 'Gehitu erabiltzaile bat',
        'ThereAreNoAssistanceToShow': 'Ez dago parte-hartzailerik erakusteko.',
        'UserAlreadyAdded': 'Sartu duzun erabiltzailea dagoeneko gehitu da',
        'UserRequired': 'Erabiltzaile bat hautatu behar da horiek gehitzeko',
        'DownloadTheAttendanceReport': 'Deskargatu bertaratze txostena',
        'CheckTheUsersWhoAttendedTheMeeting': 'Hautatu bilerara joan diren erabiltzaileak',
        'UserPendingApprodval': 'Onarpenaren zain',
        'ReportAttendance': 'Asistentzia salatu',
        'CancelAttendance': 'Utzi laguntza',
        'CancelAttendanceText': 'Erabiltzaile hau ezeztatu egingo da bilerara joatea:',
        'LoadingAttendees': 'Parte-hartzaileak kargatzen',
        'AttendanceDelegation': 'Laguntza-ordezkaritza',
        'VoteDelegation': 'Botoen ordezkaritza',
        'FailedToReportAssistance': 'Ezin izan da bertaratzearen berri eman, saiatu berriro geroago',

        /* MeetingAgreements strings */
        'LoadingTheAgreements': 'Hitzarmenak kargatzea',
        'NoAgreementsAvailable': 'Ez dago hitzarmenik erakusteko.',
        'SelectAll': 'Hautatu guztiak',
        'DownloadCertification': 'Deskargatu ziurtagiria',
        'WriteATitle': 'Idatzi izenburu bat',
        'WriteADescription': 'Idatzi deskribapen bat',
        'RequestCertificate': 'Ziurtagiria eskatu',
        'CertificateRequestQuestion': 'Akordioaren ziurtagiria eskatu nahi al duzu',
        'AssociateSignedCertificate': 'Lotu sinatutako ziurtagiria',
        'CertificateAlreadyRequested': 'Dagoeneko hitzarmen honen ziurtagiria eskatu da',

        /* MeetingMinutes strings */
        'LoadingTheMinuteSections': 'Akta kargatzen',
        'NoMinuteSectionsAvailable': 'Ez dago akta erakusteko.',
        'WriteANote': 'Idatzi ohar bat',
        'WriteAComment': 'Idatzi iruzkin bat',
        'ViewMinutes': 'Ikusi minutuak',
        'RequestModificationOfTheMinutes': 'Akten aldaketa eskatzea',
        'DownloadMinutes': 'Deskargatu akten txantiloia',
        'AssociateMinutes': 'Elkarkideek erregistroa',
        'StatusApprodvalMinutes': 'Akta onarpenaren egoera',
        'ApprodvalsAccepted': 'Onarpenak',
        'ApprodvalsPendingModification': 'Aldaketa eskaerak',
        'ApprodvalsRejected': 'Errefusak',
        'ApprodvalsPendings': 'Zain',
        'ValidationPeriod': 'Baliozkotzeko epea egunean amaitzen da ',
        'RequestApprodveMinutes': 'Aktak onartzea eskatzea',
        'RequestApprodveMinutesText': 'Ziur aktak onartzeko prodzesua hasi nahi duzula?',
        'ApprodveMinutes': 'Aktak onartzea',
        'AttendanceDialogTitle': 'Akta onartzaileak',
        'AttendanceDialogDescription': 'Lotu beharreko aktak deialdian parte hartzen dutenek onartuko dituzte.',
        'AttendanceDialogClarification': 'Deialdira bertaratzearen berri eman dezakezu "Bertaratutakoak" fitxatik.',
        'AttendanceDialogNoItems': 'Ez da erabiltzaileen asistentziarik jakinarazi.',
        'MoreDetailMinutes': 'Xehetasun gehiago...',
        'DetailMinutesTitle': 'Onarpen egoeraren xehetasuna',

        /* MeetingNew strings */
        'CreateConvo': 'Sortu deia',
        'OnlineToolLabel': 'Lineako tresna-aukerak',
        'PlaceholderDescription': 'Mesedez, konfiguratu web zatia',
        'PlaceholderIconText': 'Konfiguratu web zatia',
        'PlaceholderButtonLabel': 'Konfiguratu',
        'AtendanceTypeLabel': 'Laguntza mota',
        'TermGroupLabel': 'Termino taldea (ID)',
        'TitlePlaceholder': 'Gehitu izenburu bat',
        'StartDatePlaceholder': 'Hasi',
        'EndDatePlaceholder': 'Amaiera',
        'LocationPlaceholder': 'Gehitu kokapena',
        'OnlineLabel': 'Lineako deia',
        'LocationDescriptionPlaceholder': 'Gehitu informazio gehigarria kokapenari',
        'OnlineToolPlaceholder': 'Hautatu tresna bat',
        'AttendanceTypePlaceholder': 'Aukeratu laguntza mota',
        'UrlPlaceholder': 'Reúnete deiaren esteka',
        'PeoplePlaceholder': 'members (con voto)',
        'DescriptionPlaceholder': 'Sartu deiaren xehetasunak',
        'NewConvo': 'Dei berria',
        'RequiredField': 'Beharrezko eremua.',
        'MinimumCharactersForTitle': 'Izenburuak 2 karaktere izan behar ditu gutxienez.',
        'MaximumCharactersForTitle': 'Izenburuak 255 karaktere izan behar ditu gehienez.',
        'MaximumCharactersForDescription': 'Deskribapenak 1500 karaktere izan behar ditu gehienez.',
        'StartDateLessThanTheCurrentDate': 'Hasiera-data ezin da izan uneko data baino txikiagoa.',
        'EndDateLessThanStartDate': 'Amaiera-data ezin da izan hasiera-data baino txikiagoa.',
        'MaximumCharactersForLocation': 'Kokapenak 255 karaktere izan behar ditu gehienez.',
        'MaximumCharactersForLocationDetails': 'Kokapenaren xehetasunak gehienez 255 karaktere izan behar ditu.',
        'RequiredUrl': 'Esteka bat behar da.',
        'RequiredValidUrl': 'Idatzi baliozko esteka bat.',
        'MaximumCharactersForUrl': 'Estekak 255 karaktere izan behar ditu gehienez.',
        'RequiredAttendanceTypeId': 'Derrigorrezkoa da laguntza mota aukeratzeko.',
        'RequiredAttendees': 'Gutxienez pertsona bat adierazi behar da.',
        'GuestPeoplePlaceholder': 'Asistentes (sin voto)',
        'Saving': 'Gordetzen',

        /* MeetingForm strings */
        'EditMeeting': 'Editatu bilera',
        'NewMeeting': 'Bilera berria',
        'MeetingDetails': 'Bileraren xehetasunak',

        /* NewDocForm strings */
        'Document': 'Dokumentu',
        'SelectADocument': 'Hautatu dokumentu bat',
        'SelectingADocumentIsRequired': 'Dokumentu bat hautatu behar duzu lotzeko.',
        'AssociateTo': 'Elkartu'
    }
});