define([], function () {
    return {
        /* General strings */
        'MeetingPoints': 'Orde do día',
        'Assistants': 'Asistentes',
        'Documents': 'Documents',
        'Agreements': 'Acordos',
        'Minutes': 'Minutes',
        'Yes': 'Si',
        'No': 'Non',
        'RuleOut': 'Descartar',
        'Close': 'Pechar',
        'Cancel': 'Cancelar',
        'Delete': 'Eliminar',
        'Edit': 'Editar',
        'Replace': 'Substituír',
        'Reselect': 'Volve seleccionar',
        'Accept': 'Aceptar',
        'Save': 'Gardar',
        'Send': 'Enviar',
        'Upload': 'Cargar',
        'Publish': 'Publicar',
        'Create': 'Crear',
        'Request': 'Solicitar',
        'LookFor': 'Buscar',
        'Visualize': 'Visualizar',
        'Archive': 'Arquiva',
        'AssociateDocument': 'Document asociado',
        'Loading': 'Cargando',
        'Deleting': 'Eliminando',
        'Canceling': 'Cancelando',
        'Publishing': 'Publicando',
        'Sending': 'Enviando',
        'Requesting': 'Solicitando',
        'CommentRequired': 'Debes escribir un comentario.',
        'MessageRequired': 'Debes escribir unha mensaxe.',
        'AnErrorHasOccurred': 'prodduciuse un erro, téntao de novo máis tarde.',
        'SendUpdate': 'Enviar actualización',
        'SendingUpdate': 'Enviando actualización',
        'Attendance': 'Attendance',
        'Certification': 'Certificado',
        'Online': 'Online',
        'InPerson': 'En persoa',

        /* MeetingWebPart strings */
        'NoResultsFound': 'Non se atoparon resultados.',
        'ShowMoreSubtitle': 'Ver máis',
        'FailUploadFile': 'Erro ao cargar o ficheiro.',
        'CancelUploadFile': 'Descartar ficheiro',
        'ButtonUploadFile': 'Cargar ficheiros',
        'MaximumFilesTitle': 'Número máximo de ficheiros',
        'MaximumFilesMessage': 'Sentímolo, o número máximo de ficheiros que pode cargar á vez é {MaxNumber}. Queres cargar os {MaxNumber} primeiros ficheiros ou seleccionalos de novo?',
        'MaximumFileSizeTitle': 'Tamaño máximo do ficheiro',
        'MaximumFileSizeMessage': 'Sentímolo, o tamaño máximo de ficheiro de carga é {FileSize}. O tamaño do ficheiro "{FileName}" é {FileSize}.',
        'FileTypeTitle': 'Tipo de arquivo',
        'FileTypeMessage': 'Sentímolo, non se pode cargar o formato de ficheiro "{FileName}".',
        'CheckAgain': 'Non volver a mostrar',
        'CheckApplyAll': 'Aplicar a todo',
        'ButtonOk': 'OK',
        'ButtonKeep': 'Manteña os dous',
        'FileReplaceTitle': 'Substitúe o ficheiro',
        'FileReplaceMessage': 'Queres substituír o ficheiro "{FileName}" ou manter os dous ficheiros?',
        'UploadButtonLabel': 'Botón de carga de ficheiros',

        /* Meeting strings */
        'ThereAreNoMeetingsToShow': 'Non tes Meetings para mostrar.',
        'TheMeetingIsBeingArchived': 'A chamada seleccionada estase arquivando, os detalles estarán dispoñibles en breve.',
        'TheMeetingIsNotAvailable': 'A chamada solicitada non está dispoñible ou foi arquivada.',

        /* MeetingList strings */
        'NextMeetings': 'Próximas',
        'CelebratedMeetings': 'Celebrado',
        'ArchivedMeetings': 'Arquivado',
        'VideoconferenceMeetingList': 'Únete',

        /* MeetingStatusBar strings */
        'Videoconference': 'Únete á videoconferencia',
        'LinkAvailableSoon': 'A ligazón estará dispoñible 30 minutos antes do comezo da reunión',
        'ReserveAgenda': 'Reserva axenda',
        'UrgentNotification': 'Alert urxente',
        'WriteAnUrgentNotification': 'Escribe unha mensaxe (máximo 160 caracteres)',
        'MaximumCharactersForUrgentNotification': 'A mensaxe non pode conter máis de 160 caracteres.',
        'DeleteMeeting': 'Eliminar Meeting',
        'CancelMeeting': 'Cancelar Meeting',
        'StartMeeting': 'Inicia reunión',
        'StartMeetingprodcEscrito': 'Iniciar prodcedemento',
        'StartMeetingRemDocumentacion': 'Acordos e Asistentes',
        'FinishMeeting': 'Finalizar Meeting',
        'PublishMeeting': 'Publicar',
        'testBookMeeting': 'Reserva axenda',
        'ArchiveMeeting': 'Arquivo',
        'SendUpdatesToAllAttendees': 'Envía actualizacións a todos os asistentes á Meeting',
        'ThereAreNoUpdatesToSend': 'Non hai actualizacións que enviar',
        'QuestionToDeleteTheMeeting': 'Estás seguro de que queres eliminar esta Meeting?',
        'QuestionToCancelTheMeeting': 'Estás seguro de que queres cancelar esta Meeting?',
        'QuestionToFinishTheMeeting': 'Estás seguro de que queres rematar esta Meeting?',
        'QuestionToPublishTheMeeting': 'Estás seguro de que queres publicar esta Meeting?',
        'QuestionTotestBookTheMeeting': 'Estás seguro de que queres reservar esta Meeting na axenda?',
        'QuestionToStartTheMeeting': 'Estás seguro de que queres comezar esta covocatoria?',
        'QuestionToArchiveTheMeeting': 'Estás seguro de que queres arquivar esta Meeting?',
        'UpdateMeeting': 'Actualizar reunión',
        'FirstPhraseToUpdateTheMeeting': 'A continuación móstranse as modificacións pendentes da Meeting',
        'SecondPhraseToUpdateTheMeeting': 'que se aplicará cando testma o botón \'Actualizar\'.',
        'BasicData': 'Datos básicos',
        'NewTitle': 'Título',
        'NewLocation': 'Localización',
        'NewLocationInformation': 'Detalle da localización',
        'NewMeetingType': 'Tipo de reunión',
        'NewDescription': 'Descrición',
        'NewStartDate': 'Data de inicio',
        'NewEndDate': 'Data de finalización',
        'NewOnlineTool': 'Ferramenta en liña',
        'NewOnlineToolUrl': 'Url da ferramenta en liña',
        'TheOrderOfTheDayHasBeenUpdated': 'A orde do día foi actualizada.',
        'AddedAssistants': 'Asistentes engadidos',
        'RemovedAssistants': 'Asistentes eliminados',
        'EditTheMeetingDetails': 'Edita os detalles da Meeting',
        'SeeTheMeetingDetails': 'Consulta os detalles da Meeting',

        /* MeetingVoting strings */
        'Vote': 'Votar',
        'ShowQRCode': 'Mostrar código QR',
        'ManagingResults': 'Xestionar resultados',
        'ViewResults': 'Ver resultados',
        'LoadingVotes': 'Cargando votos',
        'VotingPanel': 'Panel Retestsentativo',
        'StartVoting': 'Comeza a votar',
        'NoVotesToDisplay': 'Non hai puntos decisivos para votar.',
        'VotingNotStarted': 'A votación aínda non comezou.',
        'Approdve': 'A favor',
        'Reject': 'Contra',
        'Pending': 'Abstención',
        'Abstention': 'Pendente',
        'StartTheVotingPeriod': 'Inicia o período de votación',
        'ListOfVoters': 'Lista de electores',
        'DescriptionOfStartingTheVotingPeriod': 'Os seguintes usuarios poderán votar ao comezo do período de votación',
        'DescriptionOfTheVotingPeriodStarted': 'Os seguintes usuarios poderán votar',
        'ShowNoVotes': 'Non hai votantes',
        'Update': 'Actualizar',
        'MeetingVotingClose': 'Pechar',
        'ErrorToCreateQRCode': 'prodduciuse un erro ao crear o código QR',
        'QRCode': 'Código QR',
        'GeneratingTheQRCode': 'Xerando o código QR',
        'MeetingVotingMustSelectOption': 'Debe seleccionar unha opción.',
        'DeselectOption': 'Deseleccione a opción',
        'ConfirmVote': 'Confirmar o voto',
        'ConfirmChosenOption': 'Confirme a opción escollida',
        'Back': 'De volta',
        'SubmitVote': 'Enviar voto',
        'Members': 'Membros',
        'Conveners': 'schedulers',
        'Member': 'Membro',
        'Convener': 'Convocante',
        'NoPermissionToVote': 'Non tes permiso para votar nesta reunión.',
        'VoteAlreadyRegisteredByTheUser': 'O teu voto xa está rexistrado. A opción seleccionada é',
        'ContactToChangeYourVote': 'Se desexa modificar o seu voto, póñase en contacto coa Secretaría do Órgano.',
        'CloseVoting': 'Rematou a votación',
        'CloseVotingVote': 'Votación completada, votaches: ',
        'CloseVotingNoVote': 'Votación completada, non votaches',
        'StartingTheVotingPeriod': 'Inicio do período de votación',
        'SavingChanges': 'Gardando os cambios feitos, isto pode tardar uns momentos...',
        'SendingVote': 'Enviando o teu voto',
        'VotingHasEndedAndYouDidNotVote': 'O período de votación rematou.',
        'testsidenciaLabel': 'testsidencia',
        'VotingStatusTitle': 'Resultado da votación',
        'FinishedStatus': 'Finalizado',
        'FinishVotationChooseResult': 'Para finalizar a votación deste punto, por favor seleccione o resultado:',

        /* MeetingPoints strings */
        'DeleteTheOrderOfTheDay': 'Eliminar a orde do día',
        'DoYouWantToDeleteTheOrderOfTheDay': 'Queres eliminar a orde do día ',
        'Title': 'Título',
        'Description': 'Descrición',
        'DownloadTheOrderOfTheDay': 'Descarga a orde do día',
        'AddPointOfTheOrderOfTheDay': 'Engadir punto da orde do día',
        'DeleteAssociatedDoc': 'Quere separar o Document ',
        'ErrorTitleRequired': 'O campo Título é obrigatorio',
        'ErrorDurationRequired': 'O campo de duración é obrigatorio',
        'ErrorDuration': 'Só se permiten valores superiores a 0',
        'DeleteAssociation': 'Eliminar asociación',
        'FromTheOrderOfTheDay': 'da orde do día',
        'ThereAreNoPointsToShow': 'Non hai puntos da orde do día para mostrar.',
        'LoadingPoint': 'Cargando os puntos da orde do día',
        'ReorderItems': 'Reordena',
        'AddSubPoint': 'Engadir subpunto',
        'ReorderInfoMessage': 'Reordenar os puntos da axenda',
        'UpSameLevel': 'Suba o mesmo nivel',
        'DownSameLevel': 'Baixo mesmo nivel',
        'prodmoteDifferentLevel': 'Subir de nivel',
        'DecreaseDifferentLevel': 'Baixa a versión anterior',
        "CancelReorderModeMessage": "Os cambios realizados non serán aplicados. Estás seguro de realizar esta acción?",
        "DiscardChangesTitle": "Desfacer cambios realizados",
        "CancelOrdenation": "Desfacer ordenación",
        "SaveOrdenation": "Gardar ordenación",
        "SaveChangesMade": "Gardar cambios realizados",
        "SaveChangesMessage": "Queres gardar os cambios realizados na ordenación da orde do día?",
        "TooltipMessageFirstElement": "Non dispoñible sobre o primeiro elemento dun nivel",
        "TooltipMessageLastElement": "Non dispoñible sobre o último elemento dun nivel",
        "TooltipMessageTopElementIsDecisive": "Non dispoñible cando o seu elemento superior é decisivo",
        "TooltipMessageWithoutTopElements": "Non dispoñible cando non existe un nivel superior",
        "TooltipMessageNoSubordersInDecisiveElements": "Non dispoñible sobre ordes decisivas",
        "TooltipMessageNoDeleteElementoWithSuborders": "Non dispoñible sobre ordes con subordes",
        "TooltipMessageMaxLevel": "Alcanzouse o límite de subníveis",

        /* MeetingDocs strings */
        'Home': 'Comeza',
        'GeneralOfTheMeeting': 'Xeral da Meeting',
        'AddDocument': 'Engadir Document',
        'RefreshDocuments': 'Actualizar Documents',
        'NoLabel': 'Ningunha',
        'SignedLabel': 'Este Document está asinado, polo que non se lle pode aplicar unha etiqueta',
        'NoAvailableToLabel': 'Non aplicable',
        'ExternalLabelTooltip': 'Este Document non se pode converter a PDF ao publicarse, polo tanto recoméndase eliminalo e subilo sen etiquetado externo',
        'ExternalLabel': 'Etiqueta externa',
        'LabelOnprocess': 'A etiqueta está a aplicarse neste momento',
        'LabelApplied': 'Este Document ten unha etiqueta aplicada',
        'NoLabelApplied': 'O Document non está etiquetado',
        'UpdatingDocumentLabel': 'Aplicar etiqueta ao Document',
        'DocumentLabel': 'Document',
        'TagLabel': 'Etiqueta',
        'AreYouSure': 'Estás seguro de aplicar este cambio?',
        'DocHasOtherError': 'O Document non é compatible coas etiquetas',


        /* MeetingAssistants strings */
        'Pending': 'Pendente',
        'Accepted': 'Aceptada',
        'Refused': 'Rexeitou',
        'Delegated': 'Delegado',
        'RefusedAndDelegated': 'Rexeitado e Delegado',
        'NotSummoned': 'Non convocado',
        'AttendeesList': 'Listaxe de asistentes',
        'AddAssistant': 'Engadir asistente',
        'AddAUser': 'Engadir un usuario',
        'ThereAreNoAssistanceToShow': 'Non hai asistentes para mostrar.',
        'UserAlreadyAdded': 'O usuario que introduciu xa está engadido',
        'UserRequired': 'Hai que seleccionar un usuario para engadilos',
        'DownloadTheAttendanceReport': 'Descarga o informe de Attendance',
        'CheckTheUsersWhoAttendedTheMeeting': 'Seleccione os usuarios que asistiron á reunión',
        'UserPendingApprodval': 'Pendente de aprodbación',
        'ReportAttendance': 'Informar Attendance',
        'CancelAttendance': 'Cancelar a Attendance',
        'CancelAttendanceText': 'O seguinte usuario será cancelado da Attendance á reunión:',
        'LoadingAttendees': 'Cargando os asistentes',
        'AttendanceDelegation': 'Delegación de Attendance',
        'VoteDelegation': 'Delegación de voto',
        'FailedToReportAssistance': 'Non se puido informar da Attendance, téntao de novo máis tarde',

        /* MeetingAgreements strings */
        'LoadingTheAgreements': 'Cargando os acordos',
        'NoAgreementsAvailable': 'Non hai acordos que mostrar.',
        'SelectAll': 'Seleccionar todos',
        'DownloadCertification': 'Descargar certificación',
        'WriteATitle': 'Escribe un título',
        'WriteADescription': 'Escribe unha descrición',
        'RequestCertificate': 'Solicitar certificado',
        'CertificateRequestQuestion': 'Quere solicitar o certificado de acordo',
        'AssociateSignedCertificate': 'Asociar certificado asinado',
        'CertificateAlreadyRequested': 'Xa se solicitou o certificado deste convenio',

        /* MeetingMinutes strings */
        'LoadingTheMinuteSections': 'Cargando a Minutes',
        'NoMinuteSectionsAvailable': 'Non hai ningunha Minutes para mostrar.',
        'WriteANote': 'Escribe unha nota',
        'WriteAComment': 'Escribe un comenta',
        'ViewMinutes': 'Ver Minutes',
        'RequestModificationOfTheMinutes': 'Solicitar modificación da Minutes',
        'DownloadMinutes': 'Descargar modelo de Minutes',
        'AssociateMinutes': 'Asociar Minutes',
        'StatusApprodvalMinutes': 'Estado de aprodbación da Minutes',
        'ApprodvalsAccepted': 'Aprodbacións',
        'ApprodvalsPendingModification': 'Requestes de modificación',
        'ApprodvalsRejected': 'Rexeitamentos',
        'ApprodvalsPendings': 'Pendentes',
        'ValidationPeriod': 'O período de validación remata o ',
        'RequestApprodveMinutes': 'Solicitar aprodbación de Minutes',
        'RequestApprodveMinutesText': 'Seguro que queres iniciar o prodceso de aprodbación das Minutes?',
        'ApprodveMinutes': 'Aprodbación de Minutes',
        'AttendanceDialogTitle': 'Aprodbadores das Minutes',
        'AttendanceDialogDescription': 'As Minutes a asociar serán aprodbadas polos asistentes á Meeting.',
        'AttendanceDialogClarification': 'Podes informar da Attendance á Meeting dende a pestana "Asistentes".',
        'AttendanceDialogNoItems': 'Non se informou de Attendance de usuarios.',
        'MoreDetailMinutes': 'Máis detalle...',
        'DetailMinutesTitle': 'Detalle do estado de aprodbación',

        /* MeetingNew strings */
        'CreateConvo': 'Crear convo',
        'OnlineToolLabel': 'Opcións da ferramenta en liña',
        'PlaceholderDescription': 'Por favor, configure a parte web',
        'PlaceholderIconText': 'Configurar o elemento web',
        'PlaceholderButtonLabel': 'Configurar',
        'AtendanceTypeLabel': 'Tipo de Attendance',
        'TermGroupLabel': 'Grupo de termos (Id)',
        'TitlePlaceholder': 'Engadir un título',
        'StartDatePlaceholder': 'Inicio',
        'EndDatePlaceholder': 'Fin',
        'LocationPlaceholder': 'Engadir unha localización',
        'OnlineLabel': 'Meeting en liña',
        'LocationDescriptionPlaceholder': 'Engadir información adicional á localización',
        'OnlineToolPlaceholder': 'Seleccione unha ferramenta',
        'AttendanceTypePlaceholder': 'Seleccione o tipo de Attendance',
        'UrlPlaceholder': 'Ligazón de Meeting de Reúnete',
        'PeoplePlaceholder': 'members (con voto)',
        'DescriptionPlaceholder': 'Introduce os detalles da Meeting',
        'NewConvo': 'Nova conversa',
        'RequiredField': 'Campo obrigatorio.',
        'MinimumCharactersForTitle': 'O título debe ter un mínimo de 2 caracteres.',
        'MaximumCharactersForTitle': 'O título debe ter un máximo de 255 caracteres.',
        'MaximumCharactersForDescription': 'A descrición debe ter un máximo de 1500 caracteres.',
        'StartDateLessThanTheCurrentDate': 'A data de inicio non pode ser inferior á data actual.',
        'EndDateLessThanStartDate': 'A data de finalización non pode ser inferior á data de inicio.',
        'MaximumCharactersForLocation': 'A localización debe ter un máximo de 255 caracteres.',
        'MaximumCharactersForLocationDetails': 'Os detalles da localización deben ter un máximo de 255 caracteres.',
        'RequiredUrl': 'Requírese unha ligazón.',
        'RequiredValidUrl': 'Introduce unha ligazón válida.',
        'MaximumCharactersForUrl': 'A ligazón debe ter un máximo de 255 caracteres.',
        'RequiredAttendanceTypeId': 'Requírese para escoller o tipo de Attendance.',
        'RequiredAttendees': 'Requírese indicar polo menos unha persoa.',
        'GuestPeoplePlaceholder': 'Asistentes (sin voto)',
        'Saving': 'Gardando',

        /* MeetingForm strings */
        'EditMeeting': 'Editar Meeting',
        'NewMeeting': 'Nova Meeting',
        'MeetingDetails': 'Detalles da Meeting',

        /* NewDocForm strings */
        'Document': 'Document',
        'SelectADocument': 'Seleccione un Document',
        'SelectingADocumentIsRequired': 'Debe seleccionar un Document para asocialo.',
        'AssociateTo': 'Asociado a'
    }
});